apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "2"

resources:
  - core-api.yaml
  - outbox-relay.yaml
  - ledger-worker.yaml
  - webhook-worker.yaml
  - fraud-worker.yaml
  - webhook-echo.yaml
  - network-policies.yaml

patches:
  - path: per-core.yaml
