apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - platform-configmap.yaml
    - outbox-relay-configmap.yaml
    - ledger-worker-configmap.yaml
    - webhook-worker-configmap.yaml
    - fraud-worker-configmap.yaml
    - core-api-configmap.yaml
