---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: envoy-gateway-redis
  namespace: envoy-gateway-system
spec:
  encryptedData:
    password: AgAJZ78fX0X2dyCoheu9rGFBgCwnvPcHSTUdNIjegagLAVPjEUjY6/IpIiZdpUqKq0RMV2kcR0M5NW3HirSYdi4C5WnxpKIrDD0qLgeFtIfTzKePsmGk9b8JaC9SIptG0tFPF4TSiuh8u7a7Phl/FP8XuDKcawrudJ8gDKnlZPaMBCnBUWgsMRsI+R5/yIQ1eIvxJwr0tR8AoNW1TJFFHecrW4mkATCHjmHqztMpHgz5l+MDRbQZuMyWOAcnRHOQpTdQyRi6bzPBtWTZVnlmT54+aGVmnCP7ZLPj5eLdynoLSI2OUuYGdcluhvgzLJWbVLeIZ2T5R8HJQoF2U3Mbw6CXyIoefCLOtaIz0hEK6CW0nKsfwuChPMfVGC80r5lAFm6C3qTTMnNrlE1yhxUwQSfz45BbEmqVqmPE1rF+lh/SmYXovh0jLfDM3kTBMuhPIcx6yv2gXOY8x/6NwlbAR/w7WHtc4vOK52CO00KHMSck+xwWwR9kA7QXsfAhVuBieHK0c6byaD7IGuyg3xSOAkKzOoOXj9SCBmnkRMQ5lETCvXN4/v6enJZOzTjbU5P/5vEanbqv90RZ8oaE7iI/tBKtEYndetnSERBVOSSZpKczx9wzqrKXhSg+Mvjlw1ERAhCNZBoFvqTf8THzT8pY2NdDFLBg8Twd+vlLMnECNwvhGDbQqaeeom2v5dyr7//9ECizz6G2IOdhTWC5a6O8OYAs2Dy7Co1zyXqx2wvqt+6E7Q==
    url: AgAxu5RZ6EiEkbJcy3+mxdrwiAUcxihRUCXVJJMa7eChR1chnGCZsCzASv3z5jTvyGAPzTtWtJAQJy2/rUS4NcrMrraTE/Va6oPBc1E4g2f6SpZ3UlPsubDLcF5WUasJj2srH2AJTnGdc0KbIqRGoccfUYW9GJveGKFcOXmgz9zHlGlncnDF0v2viWEOJHGU0AOOHmcYHz+gqiSvorptTasJjp1Pi9Fp51LSmukt8kLDMdEHpNUs4DXhsQHyBHuW3n083fXmiMqF56krgfdbGkET4TMCmsHUggiijIIJmlgSUDbEjF51ys53eDPimsEcQfzbFm/7Ab46c5+uSnVo1QszfwTeARsN4gSKVHq1JHOOPNrgmJyv9WWnRN0gjw4W673ToFDtBoap5dOoiRneG+OsALSYbYByVwtE07FQ1izAvJPvx7Tm3vsnk5OLUQE03lGcBSidVnD44XfiW15RoyDh73CsRe08twkPUcjuEqeaVjtLORrp04GAHVJQNqKLAWTqzQsY594P4O2/WdQ/ozLR4q8m8oPDoyF7YN0Nv1XWWQKOSnQl3nnZ3zO3r0e+pLX4BBgg+qhTfztp4V4ZW4VvmqPWv/xrMm0TE9UNusaMTzF4kKzxyqmeymsDUd/OoJI6UlLQtaDsmobgI2py9ZkECLBp4vao1OdzZZDyUqaZedOEJ6OFB82Hw5XSVmdyd4f6mIjrIT5RabPCnpKmD9EldDuAxqWobN7xNEwubjhDeDqhf6SKkNd8I9WZF9uTY6X2O7amIAY6rLbSgmm7Px5ilyzeIegjjlW/ExV7jCfAXQ==
  template:
    metadata:
      creationTimestamp: null
      name: envoy-gateway-redis
      namespace: envoy-gateway-system
    type: Opaque
