apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: platform-collector
  namespace: observability
spec:
  image: otel/opentelemetry-collector-contrib:0.156.0
  mode: daemonset
  ports:
    - name: prometheus
      port: 8889
      targetPort: 8889
      protocol: TCP
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      filelog:
        include:
          - /var/log/pods/*/*/*.log
        start_at: end
      kafkametrics:
        brokers: "rrq-kafka-bootstrap.rrq.svc.cluster.local:9092"
        protocol_version: 2.0.0
        collection_interval: 10s # Scrapes Kafka metrics every 10 seconds

    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 80
        spike_limit_percentage: 20
      batch:
        send_batch_size: 1024
        timeout: 1s

    # enable complex multi-pipeline logic that processors cannot achieve
    #  functioning simultaneously as an exporter at the end of one pipeline and a receiver at the start of another.
    connectors:
      # Spanmetrics Connector: Extracts key APM (Application Performance Monitoring) metrics directly from tracing spans.
      spanmetrics:
        dimensions:
          - name: http.method
            default: GET
          - name: http.status_code
            default: 0
          - name: http.route
            default: unknown

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
        namespace: "rrq"
      otlp/jaeger:
        endpoint: "jaeger-collector.observability.svc.cluster.local:4317"
        tls:
          insecure: true
      elasticsearch:
        endpoints: ["http://elasticsearch.observability.svc.cluster.local:9200"]
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp/jaeger, spanmetrics]
        metrics:
          receivers: [otlp, kafkametrics, spanmetrics]
          processors: [memory_limiter, batch]
          exporters: [prometheus]
        logs:
          receivers: [filelog]
          processors: [memory_limiter, batch]
          exporters: [elasticsearch]
