apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - collector.yaml
  - instrumentation.yaml
  - servicemonitor.yaml
  - prometheusrule.yaml
  - alertmanagerconfig.yaml
  - secret.sealed.yaml
  - elastic.yaml
  - dashboards

#   [ RRQ NAMESPACE ]                               [ OBSERVABILITY NAMESPACE ]
#
#   ┌────────────────────────┐
#   │    APPLICATION PODS    ├───────────────────────┐
#   │ (Zap Logs + OTLP SDK)  │                       │ (stdout JSON logs)
#   └───────────┬────────────┘                       │
#               │                                    ▼
#               │ (OTLP Traces          ┌───────────────────────────┐
#               │  & Metrics)           │     filelog receiver      │
#               ▼                       └────────────┬──────────────┘
#   ┌────────────────────────┐                       │ (Tails Logs)
#   │     OpenTelemetry      │◄──────────────────────┘
#   │   Collector DaemonSet  ├───────────────────► [ Elasticsearch ] ──► [ Kibana UI ]
#   └──────┬──────────┬──────┘                        (Feeds Logs)
#          │          │
#          │          │ (OTLP/gRPC Traces)            ┌─────────────┐
#          │          ├──────────────────────────────►│   Jaeger    │───┐
#          │          │                               └─────────────┘   │
#          │          ▼                                                 │ (Feeds
#          │  ┌───────────────┐                                         │  Traces)
#          │  │ServiceMonitor │                                         │
#          ▼  └───────┬───────┘                                         │
#   ┌───────────────┐ │ (Scrapes Metrics on Port 8889)                  │
#   │  Prometheus   │◄┘                                                 │
#   └───────┬───┬───┘                                                   │
#           │   │                                                       │
#           │   └───────────────(Feeds Metrics)────────────────┐        │
#           ▼                                                  ▼        ▼
#   ┌───────────────┐                                    ┌────────────────────┐
#   │ Alertmanager  │                                    │     Grafana UI     │
#   └────────────────┘                                    └────────────────────┘
