apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - collector.yaml
  - instrumentation.yaml
  - grafana.yaml
  - servicemonitor.yaml


#   [ RRQ NAMESPACE ]                               [ OBSERVABILITY NAMESPACE ]
#
#   ┌────────────────────────┐
#   │    APPLICATION PODS    │
#   │ (eBPF Agent Injected)  │
#   └───────────┬────────────┘
#               │
#               │ (OTLP gRPC Push)
#               ▼ (Port 4317)
#   ┌────────────────────────┐ (Pushes Traces)    ┌───────────────────────────┐
#   │     OpenTelemetry      ├───────────────────►│      JAEGER TRACING       │───┐
#   │       Collector        │                    └───────────────────────────┘   │
#   └───────────┬────────────┘                                                    │
#               │ (Exposes Metrics)                                               │ (Feeds
#               ▼ (Port 8889)                                                     │  Traces)
#   ┌────────────────────────┐ (Feeds Metrics)    ┌───────────────────────────┐   │
#   │   /metrics endpoint    ├───────────────────►│      ServiceMonitor       │   │
#   └────────────────────────┘                    └─────────────┬─────────────┘   │
#                                                               │                 │
#                                                 ┌─────────────▼─────────────┐   │
#                                                 │       Prometheus DB       │   │
#                                                 └─────────────┬─────────────┘   │
#                                                               │ (Feeds          │
#                                                               │  Metrics)       │
#                                                 ┌─────────────▼─────────────┴───▼┐
#                                                 │           Grafana UI           │
#                                                 └────────────────────────────────┘
