---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-webhook
  namespace: observability
spec:
  encryptedData:
    url-critical: AgCHNsJVYkFlSOU8j0DPsnAvWNkQm69On0McZrVLroCMyPerfGJGiohK/5qc0q8gIC4fv/HMSAI/ZfBgLiO88u4YTm3x9hXHk67bNX9eCJcRqMSEyXl88UvLPpCREHYZIA194BlIfIv6jn1SoC+e8bIXrblqpzGRyGRAU2Cc+nR6nH6WV0UqHTM1cTBa7WiRXf6IPoeZCP+eM5HKDxFGE+L0dNE/XjKRkBAIppxIFa340FwGErlsKoGnUzhDZJz4QN7rFEfDSU/SKxWPDn8NUVFELit/N6BH3lXIU6KmGDrWnUsmsyxqomfa6d1papHCn7vDCPmfDuEBQ0yLSstLZTNsmGXupneGta8TiUNOCyXeLFqt8pcQXGuSjUcbwMBFlnTMDxlmrS2knu8izmENE/0QBP4traTMaP6jCKn92ul4hx15R8PC/cTozucuR8XY9f2mxg5d+AUrC/tsJIW1pY3c+8vE5IgwxrwbWv5c4sFOgzuhm/jtV9+AjTN7G9xAPS+lDCqL+rz0vJUC2b/l4XA1B8fW6PfnIrGYBg3Rw2h5c3bfUHIUwxCwqVGE6V9a0kiSEUVu6MQ74HBc2euWsDLpHu3DG8TyaGk7awx3Ky+hLb7DUyxAr1y948zU1vHZmucjMnX29Pxo5PBg3LrpzLrIU6EJ0KUqqt9geG01KTOeCClGTmNP5HDRtZN2VX2Q4HNg6rQ+f3hSpHNypfImf7ayX39+xVtXDZXcNFZSc/vy5g+dMCxSyXWJ/Gzj1sY9NgUFE8mwtWYtYxlWFB+x11t7eiWudmigem1QagisbSjX1Dg=
    url-warning: AgBR3jlxMJdOogOqRCjGD7zk28uXivP7NMjqWkQ52jVwR9QnU21iWlHZNjerFklCY0kL/Qs4J5NQ2HutcAKePFug4uEWW2yUAk5mzOQlfwrl+MdoVzClULb3ZUzPoPb4XjxFOS/GskL7crWrq/YZIJewOdWIZP2PzWLKOVDmT7U4OaQ4Z4OWxHfQfu+cwkH2+d19og1FBvMTCim+OdYnhYEHGmQ/0qqk4zDITrBqB5HVRTlZW2l8LmHqP9obxWenc359K0AvJq2AbRk64n0BuTTUzZcgcGn4TQyDf9VaBI2cu9gg0g2SNk0b847+jv29dAdqNRnAaJYuTgp3qP+hjFoiLou7bAfi+MbU9UvW+6HgiybM2g+KyuBRSdPhjlkuyKCta2LEJWAwM06Aj53/Zqvn6lqZvPHT2lwbr8CFJPV0Dn884PADYU4YgSMRnmMAqlEfGfd8UPWmOuo4slG+YXGDQ2LHQgzjshcEjc21vTb0ymguQq0srnYH9Fw+gDUIBCrdp34LcY/ibycoiDHVxMNC17+tElmLps8aAXln912uefvwshoCkJSQ5BTSQIvFNN/qZ1uVt+b9wmZghwuATDiXKa/i6a0Jkg54h/d3cLjomlcEMIu14qwKucD1z0QdBKdHGcJHspkv2aQTnBDMmKunY9zgMRMZT6XEqwE5sKHyqJcW8QpvXUbHGpdaP6XQQ+lmQRGe+5fIq4D/Uc9048cejEC5bJV10Ico7okQhwZdMpO+4LZgOJqyRCilw/6vT+SIoYk4QcXtJKw4dtdmYJbsjH5CKKYhiMfR40sVP548Kvw=
  template:
    metadata:
      creationTimestamp: null
      name: slack-webhook
      namespace: observability
    type: Opaque
