---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: rrq
spec:
  encryptedData:
    redis-password: AgB0IXbn4A3sQzpaOc4k6SeNL2pBSIZ+tjNexQfkocFk6mJLT4pIHudw29RZK6y1uerZ4DPWJUvYrKcnmsrYhif486uCuDoEFmt5FSsSZc2khg2tv1zsXf1aHk9EsyuAzxp6FrqSK5aQ3N9EmbeKnAWuZ9ksNFTP/2WzPiSYfe4N+qarHYLyEYbs1jVUU5NhwS84YjPvBFdnyWw5BRnH8+YYQqaFuBoZbJuFnfzeAIWqhJNTUzfhm558f+uILOU4cKC5UKGo/Gs5WmnXnpgvwvf5abQr+sjvnrxqkUvEEqzlUNogjuLuiCwQygHRMS79oGmuillEiwyo82GUV+YY/92xrmrkLSGKBRnRGiwm5uVoof45YCow9TKcTVKFwSSzIa7cLba9AjXxkDJPw7o6EBZqh/9SfHDlhm7EP3+uWj/AM7k/q1/ENug4Y+TRzhDofyz5oQ2JHTpe0tl2WUzxpqLKec4hTizJxmHIw37b+oTnWn+qYWlYY6YoM+5NjiFzzlsTJekRm3RW2gexTn/dJ3RKf5vjcLcHc3w8GeQ5+akXePKnm/eoAzeF65u+DarzOYtEEfSVNrDbucxWZ7jEmD0c6fgKvJ7bQ6Eat/8oSwLTm14n4VUk8H5BKEEar+lS6XJxll/f0aVcCzOhiFSJ1iP8MUbo/poL4wpVM2c1UbXBIZ2VxYLc4ke2HyB7ABIftd7ZYGO8303JBoXMShQWmHspDJOKjZ0V0NwQOSiesamc
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: rrq
    type: Opaque
