---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: rrq
spec:
  encryptedData:
    redis-password: AgCDbvE4tPE95b15bTbkd8/2o7sIr3lt2Y9a1G4AW0yM+/k1U4yhqDQ3cXQpkWKCep2dmCdiq4DKSAiyndM1xjVjz5LyfEyyyoEaaumpGerqJCR0nu5AAqlfygAD8vtCRu6oGk0E9ohvjt8gcooG/nMh6IKq4LjgrtUGBIL9J/hObGz+Yclzr7SS00VqqGbHc77WslZJbve1H9RuicximbAtp+PUsg4rTBtzJ+01edaYYNnOc+avGb22MqygVgEgyT9uuPCD0ReRub7/p5FIjqEJBDR/NZ32HVtMsLY7nM9/+RppUMXZU/TBLaWuVB8Tl4XnSywhqn3hghX0ZBWTdzCOlAG+dRAtvagCJW5Sg9DSXGaFDZcsfc0d6BPrcjo0egpVoggMIcfLabN1DaIRpBHxOLY6/TClWL1f8UDS3F7ui/l6rQ+LW/uzIbVmKu7BOokesrb57RqYz0057dABskwKH8ZYk1/1Jw/fVsvedO/umXGXKOksHToJ+efkUhyq8Ixp5Ulb2EdmzzPk6WGYUiovGNkL6j6LaKlHQa6B5eCk14Y9FSGlTiZzhET0ukab9ldDeKpTat003ZU+iahxw/AcrHVpB7hRnyBuB+zm15T9B0Ye5Y3RNpWGt3M/+LvASh5/r6G75CCAvDbqpjTIjEvH1BXD+cF44ifyYK6EAJ2gcmtrJBgL8L7tk8jNvgqJF46LqUXDDR/HcsgY0j+MpicqNosuBTj9XSOeGaHdPJ+g
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: rrq
    type: Opaque
