apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: redis
spec:
  encryptedData:
    redis-password: AgB9rQPkVxy69H7rinApuaiBGF9jEKdzO8nXuKGdzOv1JzRu5JPDaqLcARvYeMmTrmF1fJ5T7Y7NGMn9XKgP00Uh3dgvvmczenolgAavai7BaWcsuIJTNBCkBtp/9nNb/c73Kx4+6zPbezhWqWT2YRDW4bi0y+T+bbtNBUlr9JPedFrkqVLeMXgK4K4J0oFK/30xyCjPYKCK5A0yv//cj2jglBcyIRMO0+CPChjtDe5GfgrQK2DzMCnJrXKOngecp8oNU05AtTeqMMWSz/zo5j452tvTst3aTBL8m0xtI2hjUTsX2Z81XlUOfi44s6e8Zf/HVz+FiMgwdDgue/cXB5yVMXtEHz+BBsIJGhQtR7N8kMDyUvx0zVLokDtAgr+4QfH7zzqdLHj1pLD/TjhME5WMXNLtk77eqZCx+WUtdaiYw2bXEFkSapjZ8TJeNCM+YfYMMGWZi+pFucGMKHHswF7OmWNHQWxiyUPAoh7fFu8sJ47hMR05+PFAirN3XLGS6s3iHQp+VPCdoeyCjNCUvID/4HVpv//3eWkxKHAev0X8yhlQ9R5lG799Fw1y/CA7T8NxYtBjZJncEX5ftJXsiI8m0BeT+HxAbOhIhSv8oosBp2i0/k35z1UvDcn5/lsKRo0rnVwzAHD5TQ42cCZq67Zmjl6oa2IK1lLgCp23v14ST46pjSP6l2UeVxwIqiUnme2zL0dtU2nacbg9ZaUyPp2JSKkMnUlm8SqRVMlQwekR
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: redis
    type: Opaque
