apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/platform/datastores
  - secrets.yaml
patches:
  - path: patches/image-pull-policy.yaml
  - path: patches/scale-up.yaml
images:
  - name: rrq/migrate
    newName: ghcr.io/joel-ajayi/migrate
    newTag: d065b7ad635fda17c47a9a449669742e2afd90de
  - name: rrq/seed-performance
    newName: ghcr.io/joel-ajayi/seed-performance
    newTag: d065b7ad635fda17c47a9a449669742e2afd90de
