apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/platform/datastores
  - secrets.yaml
patches:
  - path: patches/image-pull-policy.yaml
  - path: patches/scale-up.yaml
images:
  - name: rrq/migrate
    newName: ghcr.io/joel-ajayi/migrate
    newTag: 5c4e5031ed0a5f339f35281192f57d052a16f4ef
  - name: rrq/seed-performance
    newName: ghcr.io/joel-ajayi/seed-performance
    newTag: 5c4e5031ed0a5f339f35281192f57d052a16f4ef
