apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: rrq
spec:
  encryptedData:
    redis-password: AgAa6ZID3VTKuKk99p4pL1TrJKjmYr8yPaUbEdnL+CHcWIiOfJCD0qTRFJxJhllifn8wT+vgKWDyzwfnK30CQbraJhMEsIfdCJ3a6oIOZexMf3a63H2nYbkJjSN05EhXVQvFwUnlnupyrR8pe9qD1qyO4qGbFj774QLh5s5zEOmBU3h/DfYnQ0DIDTvlq22vFtavBUbPB06d7N2GXe7EERV1LFo6fpyGqR0qTkoDioRDA4wDo8+QreNjG6JJ6ZxyzpZvJM47gLZXBrTIsu4LmYilpCHfcyA2bjBPVrFI2aUExAOFEb7q/FA017fGPsIJi/yRPWOVaGCkJpO2AwC7zDhVvnbwPK9sc+qfmvvwskWYcb5gCY5MiF+XkLsfjkai1pq1u6DRh4Vkjy0LGFynC/sXpTrzU1nvtBcC8rOo4gqJX3BpKlpvTknEgWq4g8ekhcEuCIEWe6TZmbm+JPzKzQMHMYv61v+Acy1LdIxWtJVQ2z7QOHW8w4Lk4E90+cwtCFA5D08TdsVXez8T48CxNUHpb7pclFvjIVGLikyB1OAkK09ch4307cPN5Wup72jgNGCKCkMz4y87EbqYwGYslHGF3g9mcGsi5j6PXscy8RkPcZJ3TuBb+MMYBRNQlFVKev6xzCtyUeeA3cpPDo0Lb+Tdg70YHz5zb83zwWwoJ0jpMWUsBmBDb1AN3NOzQanfulHqzEyR1w4cVP546o3dle0Ig5n9DaS8z88BLlYGqElomQ==
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: rrq
    type: Opaque
