apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/workloads
  - secrets.yaml
  - services # prod-specific service overlays (tls, gateways,network policies)
images:
  - name: rrq/core-api
    newName: ghcr.io/joel-ajayi/core-api-go
    newTag: d39e0ce96b6f0b1bec7d4a8fe7a61d852895937c
  - name: rrq/outbox-relay
    newName: ghcr.io/joel-ajayi/outbox-relay-go
    newTag: d39e0ce96b6f0b1bec7d4a8fe7a61d852895937c
  - name: rrq/ledger-worker
    newName: ghcr.io/joel-ajayi/ledger-worker-go
    newTag: d39e0ce96b6f0b1bec7d4a8fe7a61d852895937c
  - name: rrq/webhook-worker
    newName: ghcr.io/joel-ajayi/webhook-worker-go
    newTag: d39e0ce96b6f0b1bec7d4a8fe7a61d852895937c
  - name: rrq/fraud-worker
    newName: ghcr.io/joel-ajayi/fraud-worker-go
    newTag: d39e0ce96b6f0b1bec7d4a8fe7a61d852895937c
  - name: rrq/webhook-echo
    newName: ghcr.io/joel-ajayi/webhook-echo-go
    newTag: d39e0ce96b6f0b1bec7d4a8fe7a61d852895937c
patches:
  - path: patches/image-pull-policy.yaml
