apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/workloads
  - secrets.yaml
  - services
images:
  - name: rrq/core-api
    newName: ghcr.io/Joel-Ajayi/core-api-go
    newTag: 692b2b10391c92eb60ead8a58a04670f7092cc58
  - name: rrq/outbox-relay
    newName: ghcr.io/Joel-Ajayi/outbox-relay-go
    newTag: 692b2b10391c92eb60ead8a58a04670f7092cc58
  - name: rrq/ledger-worker
    newName: ghcr.io/Joel-Ajayi/ledger-worker-go
    newTag: 692b2b10391c92eb60ead8a58a04670f7092cc58
  - name: rrq/webhook-worker
    newName: ghcr.io/Joel-Ajayi/webhook-worker-go
    newTag: 692b2b10391c92eb60ead8a58a04670f7092cc58
  - name: rrq/fraud-worker
    newName: ghcr.io/Joel-Ajayi/fraud-worker-go
    newTag: 692b2b10391c92eb60ead8a58a04670f7092cc58
  - name: rrq/webhook-echo
    newName: ghcr.io/Joel-Ajayi/webhook-echo-go
    newTag: 692b2b10391c92eb60ead8a58a04670f7092cc58
patches:
  - path: patches/image-pull-policy.yaml
  - path: patches/instrumentation.yaml
  - path: patches/local-resources.yaml
