---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rrq-secrets
  namespace: rrq
spec:
  encryptedData:
    jwt-active-key-id: AgBzNtiM2oTXquYdIlDr/baHE/N3446Cko2IaQwjMCGtWvYZThmm+mQIhSGTecZKBGzgqUre8F0r8VIAu+67u7p476tt2Ws3Ae2Qzoitwp35o5hFfP9HljkWib91Tyfc1LjNvAeLcHy2u/RPMTdPbGwDQHzsaMCuBMNy77nXWUAXkDAKV9g8fFJ6yEvWfW5FyOyxaDJ9WqeoLh2W30dwqpPR2W3/GpNpr0XmzeXnRByBfYiSgI0q2WqJEcZBHzgdzz7F+Up4zOpZ5xrcOpen+B5MUraZ9MfhgWmXFrBCY/3hLFKy2tPqKrinGpD6snI1UyVTzDDibmM9wz6xhXWDxNgr0XXaPiOWXOIf0f9CBHOeFNCa7aA6nS1OoY7nDSjzVoknn0sPLa/O6tqaymUyModA9bIpwrsrZ+RtXMwx6mry1NkDS7I7TqLJV06hMbG9JGPfZMmxdpBKzP0NB0R6lvXAr3QAaOqHGhBqd39n9aDReL6zuP5uTAwvSmK/dHRFFLXCCHYLngnPqNlrCjmfAKDthBkgNggnFKpStBWApJz6KUKnrt/Z2KHypaAYGnyBjh22iSj3qDV01IDvcwQ9Djdr1dzIcjsLkSvWhpUv4CMWYhh6VSZKdCZHfsNKpaSyVj2BXbVcUOo+xVLdofKJbgvNaDQ8z5U2poXKaBL9vFhIRwiitufJw5EcdvcVPtF83QskQO+bB+yYt7tQ
    jwt-signing-keys: AgA3Kd5nZXXh8JO/2HppS8uBqAQKLzljcPU/aOgl2Pa4WWXBFy6xWuUktPVteFXBkHbDfaqKbfQ0IokOo9UEaMF8kPccfYtI7V3NElpkLkNVVVPOfrcZzIcIfybli1Cex+Lhgie1RFzx/HPlRvB9tqciRc7ugjp+8zkdrpZBl6rZWYMb0lYN12f7liKg7kQR3WL59p+FGSAFK5n47JQ4AWQZaICECRosWTyl7Kt2XQnBaY2y56jX/tQ289alQAlqcEkgEWwEU+unSX2iOzA0zgVYWx8sqzzGqBJHukiEBa03eU5N6kq+NhDHW23ZOlJrgkAA5bJ0uk2uxJ3jmwhTJvCserlnj5SupPbzhM/3mHLK3Hqw3dSoc/L1YYKJreHX29NNFHQnb51JqvzsIvTQCflqte1vse2G0b1loAt8X7py8rsNNN+RntHMeF/+bbDuDJo+R26PNCvqQYSnDPhbutD0nWyAUr0YsUV9xMcrXZrjr3/NYJRuuYprt4ruDMcX2f1xaqjXfsaY70PxnlxeMXFQj6AdfShmEp+CxyIRckpPJPyylFf87qVlIXPftj5FyiFF3xNdOqirumqXdMfd30ABwfFWnhKaphUWy/PSUnV6unHZh9yrHCSHC6zhVci+ZrJzNXcqXQhqHvFSJqXEhjfqALPC1GIK/6yCfAmgILM9w9rHvwz/gdgM0eP8tUVRpaVibABVqD0fN8xRDGONH7hqGO1EwtLrVldzTjPea4U6hMCDNEGXbyTN5VaZfQDge3CX4zM0yEhMCdunQTGmJXtqXS2RhwUBPJ6M6pIzk/QpBZONjGDrnMnORp+E3vTFKQcobT6M3Zbm8nMwivXI15hgGHh17PKHnaRyLUbOtv2YkmMwq5i0qlT5OCVhnoO4T+JhhxGFlEP18vvoZPlrGCXEtd1gfK4e1q7CvVUrUeHU7OoFSGfNGYLAlzfA69dbCb91XawZJdPyCK/XmnqQHlDz1nu4rjSpDdeWJmNw96XCMPDT0g5bS5DcihA0Psrxnag7DfSZA3/GPXaUXYFk5GiJctSTGk7SqA==
  template:
    metadata:
      creationTimestamp: null
      name: rrq-secrets
      namespace: rrq
    type: Opaque
