---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rrq-secrets
  namespace: rrq
spec:
  encryptedData:
    jwt-active-key-id: AgBdevkopc2R39E9tzY0KBTqVOUrTxUPxhna4NLbNkHd24ktPXFhUjHolU6vWEmKHnrm89qkuRzubtXr7W94h4NBawF5E14aZsMb+OqoZO8U94yyof9hPjlJ2W5WLc8yykm9vZ98gL2DrvjPgUBmGqbQQripQsKlN4mV1jRiTPQ07nIC5R0CLUWnqMBi//5SUHw77IRiRpHZbmUZm04I1GBu4OA628MXOigeARrcbLdSjO4bc/s5edIjMyBxTpNRjgtZxss+JpMqUa60sd68iw7b6/mY2h4yB9gqAkmgWILE+rrfL6YXJArsbu5bHRhmMbmIUk8QLxuSbfdVLeoQfhvo3Xr+vTtTX0uBMBD075+7D32xmOYbJVvedJ76dvrMLDhcAX9+57jcFxrbCxYHR8Lr2t88K9OHNkz0vOPv6OHcGt9DTLDIusDUpWytFFx36x8pz6jczZxhh791tAXyu7iMzP3YjAWjhSZtEePev4UJRfO7ZtSBk5+7ontR8aJX7E7nAb3Vou/yNMdvcTBAGj+7haIQFzuILZvkMlBfvqYh7DzlxlGxcIp2VJiEBQLHi85ymzJz3/y5qIneD3pVQkAvMqJSMFBGEbIiZf/n0wx6NcxFB/WwSS9WdLonmEeC0Ev7yBkcLQBGHd5Aliuy2ChEKMP6Imn7OV7q+ZgUoatH73QE6Jjd06gZEDByNkpO8RcRFVgZIbc3MJZ1
    jwt-signing-keys: AgAfR4EpBbZMiubD+z81IzNdcX47KoJ0Bd/hSDGvMdkVsSv/6ylhAvOSPncoHORKW3DUklXS8VTYRx1NVTIqio+z1ESiLfqY74H1LHcenTMyO9tXIJPrxjykp7j6MML4ccZfMOaLzbyS9GY6PlQpP+FnlF0P0llMvgRkZkqjpMTzUe72Py8qfeHHp2dcg5UECOrHczv6oOqr96d9qk/QrlVGptDGTyPTU94SAc0gKYofLa2AEHZlAGDA/xyILunxNkeP4dU+oRkqzkA3/gJCtsl++XKU/YzeDrobd3BRqYjtXw9PLAeKnlT/n9lrxJrHjYSTSYfu62ti/paAIOPQfyAOKhxveZ65LLmhXvlpGqbv7+Dthr+9JLY2jW7lRTzL36y6+NwlTud7RVcH8IIfqiw3NyAP//AOwM5skZK0VfwXjSvnJdPyH7dvxaGNaM50HbtnQE7xU4ETTTc4uGSGlKJDeoeU70ZT1qmz+zuY/7SiJkgG1ioM9dVVsuqd/Fc0T1ydWWuZUMPrcTOG+SaaowzjPLsyqX/aRop4ihN3Pqn3sJ34Nfpk3xluLd79VsIUs60aQyoYtokXb6rObqO406xWsSEKSr61oVLVVIPl2vvcbtuJSJZxh5zdByUAP3OpgoEAYOgztEaKSOxnvhKn5DrLu1JSqb/4YlW/+LYDNVeCZArDFf6Zq4iVXPfO+3V69XhwDoVSHmmwjpWsV2GV1BlGRTEygfMED6bpVScUJRr8fuo1swkrTZZY3vGl8nBE0aF3Z1dCxdUmzidu3IzAuIHNiRa8aG9c6wXyzWF66H3hhCzBQpj19Mn2CAwRWp1hEOOoP7auoyaHrF3u2TRtNyiw/iH1nXEFCU+ZJbxbVsTGBMNoHHjaQHsglifUzJjxg3Z/yfTWVpbLuvUF82mBuHQU3xVjWfI/JGj8NzO5+RdMMKg9kW2/G8OWEyUnMr2ZK5RPrgG+JfkYBaLYeOPzT5clGq9RVxjOftgScK53efMVdTniuaKLUTomCjZpm5nALyOuDg9yIHzlvLOw7Btw3WCiqNjcF6J1lQ==
  template:
    metadata:
      creationTimestamp: null
      name: rrq-secrets
      namespace: rrq
    type: Opaque
