apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rrq-secrets
  namespace: rrq
spec:
  encryptedData:
    jwt-active-key-id: AgCgPbUxmxzvtMEH7ZNjQ3MSDastTa+CcWP3z/AhbBaq9cT0/UkSc+4O7pTYf4+cSCSpOp+r9VpIZhfrhkayzDVaB2/l0oMjKsxqNTZM8KPeTj+74ELIcblw4xvGc5MgULnZgfYTamfZAE9sJkPF84B6dIezw4cZ3ljWrGp1K6Tsg5NIgSx+OVHBs1Ggi75PgJRJVUqq7ZNeKqRiCmd1EVtkV7DM24fs1IYKSV0TIVSskW1kYObvV4WAbrfIMbCBERuNtPGfjZThhS534MOvz96LaaXb5jxS2DWy01XR3uiTn+ZYnxjS44ENzKfH88emueFKlaV7lQcylO9MgbyGmm+iBTthhRRSOYuCMdDOru/MlJDKfdy7IB7D4ahmTLtv8yuCXorqavqqnC/DA0xOR6eMx6E71wXK6ee3AZF/I1Tzqndm2cZXTcKY9DoqWr8cXV9Qquc/A/KOp9OMhezbgHJrm6Wb3TX1juQFsLk8mHX8x9AuiD6LzEOTIEvmKvtUlPv2wiKw+PaRjukH4hdF/X4CSLrpfwnEf9Tx4QhRd5xHnlLiYT/vV9st+YAqtewY4nExF696heAV1LwtNqkfHbkW7CgbPhMlY8qo5h8FkVWxP6nQjw4vRTblGfqA1nC61+1YxjDOWYg+/XTKEY9MfXzSK9vJ8DrA2dlVtmfSssMA9Ej3V+fXxYIlPcN/FyTx+iL523YYRsef3QWkQw==
    jwt-signing-keys: AgCrMIpqVXDDzsqOwSHa1CY2CDH0tB+H79gegEEdTqj9Iv79qDUcjEQiGWnHmmeg9sMDC2ZZgaFwFTKK072ytmhRaEP1eEK9rYhQDfItEP4r0d9O/QY/3YDeJOhWi2GiSyeVa2cSygbyU3RAhhsa7i58wB0fvDoA0+DEl4COqIxWj1TZG4ltjqN7bmixYhNMPVNHSyBHIPePmyzVQqsPzUmWSjZ3S8RaZU3Rw1DLiWw9sfKVw+EaBzCdWn+/3znkt8kLLishlTW7vsULzJuCF1gIw7xjsNRpT1xTPeNLgX+9iTD7octG+30uw+roHvgmS6hSxAVaYdjGnRNCDiM0JZ8jkSjpnRKNF1f4HStmWGGjaQCu8xvfzPXbrVCO9mUgvjSaVrrlDsDEMnzDS8qrk2fI973REWBN5AdfCatZLG4Fxiq2EBXD5xujEjp6qdMgxCgC3AdywoswNJtIU2qdQ34VLt2QwkbheZSKjHPh81QUW6Nhv1ObZLXWS+XO3bgB01nwaYZrHsJjue7UdGWhl6qtXOyENgyJkvvhupB9lbYgddiv97enpZbKFTKYj3PX2D0q7VQjxZ3zUcAy7Vx4VG4JfofstEo8tlhy2CMzMwaeGmGagpzSAx2sKWmsPbGVoGFmxpqKIyOuSiyrMYlMfL6m63nZsbKECH307XAK1dBES0SUEyeoXCRniSnRdeFvwswO5KgHSglexT7j0qmqCxn4qNKUt0itgxScS3OeamOc72ArNnrkJyJMlOk1Fl4LfjBYhoc8SJUH87uMEC+H/SEbIizapZWzAJQ0+TiLTu216ZVOVB66/Ket0WxNjcteePK+luk6vxXxXJmozODPtA4iugpQAVGPxKLa8uzUor+sWPjt9AUVRQ9noCeJqoWXndkxD9dgdZlLID5pXYb/5AtadCxxxkQE+EXR7o9bH5YlJe/hxCPjGmndEU7F0qTSbQ8amFvnkp8jt5DVBT1R+OxSr0nV+x7j6yM3WlpnnH6+g5bJYUwL6BS9VJMyvPKWNnPcmNBQYBSoEf2WgDJV0UM3Glv8Tn1j7WYylKAAQwH7hJrAlMuEfJIuWWKzDtt/XKsjx9MWrN7XH4d8/D2SS0jr1KKZzVQpTuo7onq4sSYqKUf0Qh8+P7qbX3QwqKm4L9Xp04WkD/zkDaOkxRMVt9PhkNgWED89DowbDjA0DdJdIIpvdjnUTh6QOvxRsIjO8Gor0p3p2Yl5VfvrJqpmylZC7Mc+v09w181uB3ExYYaWokLKh0qcxSC1LHtGDTYTiDxPt2qfa45Jf4BV08rlazoNi7mgbbetRYm61z25UNtQ4NyfxHYXhHZ7wUs2mx1kXT+zyUlWa7Q9Yb+juf9SKggBVA33LTI1rSxpgIOiqp95IIRtCvvMrPYT1JcO
  template:
    metadata:
      creationTimestamp: null
      name: rrq-secrets
      namespace: rrq
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: rrq
spec:
  encryptedData:
    redis-password: AgCPjmjj+yZBQcDfWYA4mZI6XtYYMTgCdT6EdHEABrpjc0hUEhAWZnlnK/3NEx96fu4XYKoKvsjkK9Kow14Tf5mTlJYjZ9ysR+kKpr9HWPlV88n6vnBZAbTTWDEVTmjaXqSFU9g3bFHw1Qulis2spyFb5rocfs5s76Ry+2BcbaYRUY+2yqKP8Rb0QDd3gaUVa4uzSon2eSbgRiLj2ZFspi8W92dKYtvc5AIzs9WmscSMPCQYhGc7Akwl9byJXdPfD5s4frU2hCGCJIdqoZjvZXP7CJAyVjupG0Io0Xogn3nvz7G5r2dNHZ7/KjptYYuja24uGQkMuptwOUOBVHUOmzF2QPXV7M79pTkX3zwWwqSAJ+CDJkAaWtGcmb2fWwVCysCcb4YTVhq+xFBcetbt6SLFRyY5vYmgkHA9qfChEHKd2dziUwA2HXjd4Z9s24TBM/rg/Wlv/7YDvJy4o6fUddwDtnL9o8OdZC0RWRTT/Vxru0yuh5FWpMV1OQRyD+4u2vROg6yvtwH2sR2/bRHXojK2mvcP/jy3Bd6HVM2IqmP6l+RrRZoP4AnpDTbRsbQRw5N4ysDcyvHi+wWyybJD83xGJfRgewkW8Hy5GyyXrvygK+04//9eq9dHPh1Sqq/SZALBczRuRJviw3Q+NvKENU7ByrFpp9Z180X7eNiQz/ez6IfmQNp243Fn/3QJ4EONn57wlNYsMHf+Vn8MgbYQHu8vNkGnHdcFizeU4a5/JUKX
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: rrq
    type: Opaque
