---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rrq-secrets
  namespace: rrq
spec:
  encryptedData:
    jwt-active-key-id: AgAOs23qwqrcnLtmOL/RqcyG52NXKyGFMGIn/vNX4ZTae4BVGlnFFDtdLnLyx0l1B+KN88uh0v+yu4TxfBlg9ifAVdlX+u4E3Qx0p195kLbMzkM4SF04K0NcCVjguP+B+er+tnlxoIBajvMkGtWV7YYfPCoMIWA60pRKZWB4xWsXPXm4j85FEaKejyLhFIVKrYHsx1jHA5tA/f3+ICUcJj3mkwgLFKXfE4ERw/Px9K6UYqDj13VFT6xvEvW4ze0YE3ySNUFVLhC0SYsSfY/+bpgAZaU3kbk1uz3uv52iAFZ9ws61EVdb9+Ne6wD1bIg4UQw9g8ojNJXBCeCQs0P6GIgGmTKce1Y68Iso9owUipNgc2c+dRYu8K1MC4L3EPv2WJUhGcMcYUIAbt/3rlAfQM78CpFvdY9rttGD0F17yMvDoeRXIOxGudo1ZtuyrJzKoyuGZ7GRKkMJB48eJN4GPyI4379wODDgDVr3OE+RK4jcBWIIRtPnvnyEDTM1ZTjBOJE4YAjdyllRmoMQZE44lkWoNunAjvgHm+rUUOA8KU7w5rhwVwuX3sT2wGRY1Y72St10imMMNq9o1WLlIrlMZDfNU4CHkxvAV8P59uqF5MyEcc7GUi1lvm9KiM+QTy0iBWnz+5TGFQbRLYgs4UyJgXy8DOU9Cy/CpR/WiH+4xSF/yBSPBDpgkdCTQm0HMLSmBwvlpAie/2D3xkXkAw==
    jwt-signing-keys: AgAoq/C9iy9mFacpH4lwj+5BS+2Ih0Gt7VrOX3Ckj15WqyEOXsLkWQpKl01OJp8akeQaO80PIDkcBFAhT6FVF7U61TKhAPc9e/qv9E0uHLy2A8Ttu3GXfv3+MbQKcsoWeP4bWFDENdUMt5QNakvrz5m+8FtXoU0Ovps7fGWwvQmDWVU5DNqQqAy/fkujNBou/Fx/IUywC3u9PuO8lZL16/fzI+bo/a3rZKa85WJp3NzooyGY//aGs5bAKqGScopmManH/gpIdOTZK98DOn1UZhzFIFOYGBIpsflDzDizYh2vP9JQYO3z4YucPKumdgp6ojRbhsCav18JD2f4FoY7wPzcdrWxO+TR56WTV1clIew7eK/9IzTdcfipUUBAcJy+Q5pojyZEysGBzDyhGJ2bYtf6CmBaK8JFzNC5MibnjuwiOMVp137hxCSIx0j8oLNAX/BA3iZxs3Bxcnx6xMcXBEvcxVpgesvqJmXA67ChZ0TgZDYi4TCz75azuNW6TtIg6aLe8AqlD+TfQft9ZOejU22jbK2TUWUL+DkJZByIronkG/9uWR1G1rln9yXG7WO3e40+3cFXAWFAQOTIzucOZz5z9jg+84PXroOXhKyA34t0/sCdtCMInQeJ/E0mUF17LLYXb+6S2KH7zrrKLRPrh+w33rlYlA7nFaUiU4PvxBFxq4T6EW8omw2rI75axOOjQcFrhQbpnjd9Ai5G4I/do/ay/+JSTl6DVUYUv4xaxRIPRi7KbE1migW+1j+h8X7QtAEpH6YeKYm2f7KQmMDrytvT+bl7Ia2GepySEut3GWZxYEFEYtow0AVb2baRsCP2zy13QrBNaGUD62uvM1EpKM+hh0esxNARvA1V1MUlktDzJ1TihhKj+QoD7kiPO3cXO1+oIhRAPgPqbtBzQKFB3a5BNbjbY67MnfjfTPAzXBqwVLZheIo7rq+gH1IBsQqEJLVttodlr/v7airo0DzOIVANNBbkIbE0cz2pzj/V6F2XE98nMJBYBddQsGRFz9SKUsJOtQ4h2RnEpZHy0/P+0Z2o/U7rrGiwIJHMpkv8d8CmLnk+ni+dj/c2GtWCMZqB0R90Ogz0HYoaaPbjs+1fw55JTJBIPr92zs9xr1PWffoAT3RR4uJMykInNar7+hXF7MmCrHHMOBWXGFv7acBHX+5seq2gpcmEOfp6PxKFPRmf8JyCqi0fz4etXIkqeDsP4Q6BvQaR7KYFWpDCiI2JXlYuv2RFe5+pyF/GXneIl40to4D4Qj3frne6dL6UQRRgXEXizk4UIYvZAgw32UseZkozMUcyCOjFl+LcGVGQobNjA/LfTt+KUdNvaul3eg9upWSnRL0Xin3/fQK4TjcV5/TJrHkIAAdjFD2Kyfxmd6G4UWw9PWEvNaiXZwE3
  template:
    metadata:
      creationTimestamp: null
      name: rrq-secrets
      namespace: rrq
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: redis
spec:
  encryptedData:
    redis-password: AgAa6ZID3VTKuKk99p4pL1TrJKjmYr8yPaUbEdnL+CHcWIiOfJCD0qTRFJxJhllifn8wT+vgKWDyzwfnK30CQbraJhMEsIfdCJ3a6oIOZexMf3a63H2nYbkJjSN05EhXVQvFwUnlnupyrR8pe9qD1qyO4qGbFj774QLh5s5zEOmBU3h/DfYnQ0DIDTvlq22vFtavBUbPB06d7N2GXe7EERV1LFo6fpyGqR0qTkoDioRDA4wDo8+QreNjG6JJ6ZxyzpZvJM47gLZXBrTIsu4LmYilpCHfcyA2bjBPVrFI2aUExAOFEb7q/FA017fGPsIJi/yRPWOVaGCkJpO2AwC7zDhVvnbwPK9sc+qfmvvwskWYcb5gCY5MiF+XkLsfjkai1pq1u6DRh4Vkjy0LGFynC/sXpTrzU1nvtBcC8rOo4gqJX3BpKlpvTknEgWq4g8ekhcEuCIEWe6TZmbm+JPzKzQMHMYv61v+Acy1LdIxWtJVQ2z7QOHW8w4Lk4E90+cwtCFA5D08TdsVXez8T48CxNUHpb7pclFvjIVGLikyB1OAkK09ch4307cPN5Wup72jgNGCKCkMz4y87EbqYwGYslHGF3g9mcGsi5j6PXscy8RkPcZJ3TuBb+MMYBRNQlFVKev6xzCtyUeeA3cpPDo0Lb+Tdg70YHz5zb83zwWwoJ0jpMWUsBmBDb1AN3NOzQanfulHqzEyR1w4cVP546o3dle0Ig5n9DaS8z88BLlYGqElomQ==
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: redis
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-webhook
  namespace: observability
spec:
  encryptedData:
    url-critical: AgAuditasKwwDtkuTr4FFKgjzxGzF0sBlTVTeaN4eaMiEQ9K13miHfWNCi1J+1AZBWsYOIx7uBgJhbRSkoBBPDdyKjSZb9yO9dZLmS/GUypVWD+wAij2n99TMQ8MBRdXSdvggTOzlEiT5vlSceYgUd6iRxB5sd19gXutidKSbluB83lSfY3hbLrf6daX8uJ2EBX+6YmrRqRGoWW3cTPEZqidAc8ozhWp76Xk2iiIzpqZ0tygh3xxxDn4LQMpMztRjg4WGT7uF60/eEi6SDZQV4rx/FWswSwbbsRzliNE4REIhT3Th9RbahPcSA6zzI+PeE1/cbVpN6H10QnTlT+/Bci7VgyJNdt7ISL6hDLTjjW1qeC/Vf/2SbcoRtCwtacFMcPZBcXoMa1LHpijhq2wMDkluQuysKhafdDaiuT64sjhutvpuxKRgRRFRTpOSFNr1k+ZBam0BxdYQZdLumP6uWxlG+zzUez77P0OKHGZ2z3aBHxLB79lg53DO5ZIupdn471P4wh25RmZI8VgghKG3/d1IjiqauCtf2J37A10S9xlY0EIaSx1Ps4sZfj/hhxXjAnWM70797Q8wcgEZGDAKVlCvnQhSTlHCkQpRd15NjBbUceEk9HPVDEM/jHug3MSeuJDsW1IVEQSPt990lZHDn8sFlQN+Nmq0X7rjzSWO14TrTz4ugbT3LAgXQMrk57kCEPcAZvk8HcqCmxtfrSUGu1Ovv8yXcEKcM3fIVyqNyJ1QqD2IhJwBpHXFKJmkRh9bdnw2bUAypDLTDRZxJU6JZ5SQd46l/rj0lv3rlJEDWl+RBM=
    url-warning: AgCNrAWkhAy3DVIS+pyA0rpcaV+K3QfIp2Hz6aGFuefPWZtOKtG/DBrg8oaEcYRtnj6Ics858gHkgMnQk/w7s6LpUGwkrE4/FZ2V1HoyhHM9ClkMoxvg0QGDT+LZoVO1Hq5L7UwxWXcE5ol5ySm5McXdWBJ6fN9vEN/uHVXSYdvLCZcT3CCCFjYF82RZeCqpbfWADTKvgLj+nI65adQQ1MG5fEp6/v0Pw07f7cPaSz8wDqv8v9OmXS/MvWbw9cps3V9pTtx0trAybOHmx674UFTGWqC2PHet0BRAhkbgbRLFtmAW6xW2sHRbZePCijEzJEUFqTg3hPpGK2vs+DGmWaWYjeBXw1XC8jcwmOqRrCXLykIXXr+47cVcOuHae5tHE9ZNjZ2qx+KnPU6XM7gq/bOzoHk+jXQCp6bLqc7qR97VW7qq4vNG3zWiQ7GMMpBSh22Vytdv1tC2YzLcXBry7DQJJ/jPnaabmXIY3Q4HsloC9OAd1WPbcWKm1YZnp715goHmAzr5DcZn6pLDayFJht+fqKpZao2haiqGVHaQDLzUF4PjUUzS34Ckm5/sn8M81S6xeEdPJajxx5SHebUHnu6TprH/aYtth/SdDSocN7kI7DMdHbU55KTox3GD2sV6GtnaLuGtuyaLLvZFRGruYTBi0seTDwD6gn+XX6TlTG0YgPTYwA3YvfGYfg6Wvljuy0I1hfiqoApxo6Gdmv6thvvL2UfjNhRdd8uSd7Q1Sj1V+YCv7Va1KGDTbJq/Y5vUaYYKLb+VbA1Vr0oPhdvt7TzebWpHwyuxKFUojKlSwBSDBOQ=
  template:
    metadata:
      creationTimestamp: null
      name: slack-webhook
      namespace: observability
    type: Opaque
