apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-webhook
  namespace: observability
spec:
  encryptedData:
    url-critical: AgAuditasKwwDtkuTr4FFKgjzxGzF0sBlTVTeaN4eaMiEQ9K13miHfWNCi1J+1AZBWsYOIx7uBgJhbRSkoBBPDdyKjSZb9yO9dZLmS/GUypVWD+wAij2n99TMQ8MBRdXSdvggTOzlEiT5vlSceYgUd6iRxB5sd19gXutidKSbluB83lSfY3hbLrf6daX8uJ2EBX+6YmrRqRGoWW3cTPEZqidAc8ozhWp76Xk2iiIzpqZ0tygh3xxxDn4LQMpMztRjg4WGT7uF60/eEi6SDZQV4rx/FWswSwbbsRzliNE4REIhT3Th9RbahPcSA6zzI+PeE1/cbVpN6H10QnTlT+/Bci7VgyJNdt7ISL6hDLTjjW1qeC/Vf/2SbcoRtCwtacFMcPZBcXoMa1LHpijhq2wMDkluQuysKhafdDaiuT64sjhutvpuxKRgRRFRTpOSFNr1k+ZBam0BxdYQZdLumP6uWxlG+zzUez77P0OKHGZ2z3aBHxLB79lg53DO5ZIupdn471P4wh25RmZI8VgghKG3/d1IjiqauCtf2J37A10S9xlY0EIaSx1Ps4sZfj/hhxXjAnWM70797Q8wcgEZGDAKVlCvnQhSTlHCkQpRd15NjBbUceEk9HPVDEM/jHug3MSeuJDsW1IVEQSPt990lZHDn8sFlQN+Nmq0X7rjzSWO14TrTz4ugbT3LAgXQMrk57kCEPcAZvk8HcqCmxtfrSUGu1Ovv8yXcEKcM3fIVyqNyJ1QqD2IhJwBpHXFKJmkRh9bdnw2bUAypDLTDRZxJU6JZ5SQd46l/rj0lv3rlJEDWl+RBM=
    url-warning: AgCNrAWkhAy3DVIS+pyA0rpcaV+K3QfIp2Hz6aGFuefPWZtOKtG/DBrg8oaEcYRtnj6Ics858gHkgMnQk/w7s6LpUGwkrE4/FZ2V1HoyhHM9ClkMoxvg0QGDT+LZoVO1Hq5L7UwxWXcE5ol5ySm5McXdWBJ6fN9vEN/uHVXSYdvLCZcT3CCCFjYF82RZeCqpbfWADTKvgLj+nI65adQQ1MG5fEp6/v0Pw07f7cPaSz8wDqv8v9OmXS/MvWbw9cps3V9pTtx0trAybOHmx674UFTGWqC2PHet0BRAhkbgbRLFtmAW6xW2sHRbZePCijEzJEUFqTg3hPpGK2vs+DGmWaWYjeBXw1XC8jcwmOqRrCXLykIXXr+47cVcOuHae5tHE9ZNjZ2qx+KnPU6XM7gq/bOzoHk+jXQCp6bLqc7qR97VW7qq4vNG3zWiQ7GMMpBSh22Vytdv1tC2YzLcXBry7DQJJ/jPnaabmXIY3Q4HsloC9OAd1WPbcWKm1YZnp715goHmAzr5DcZn6pLDayFJht+fqKpZao2haiqGVHaQDLzUF4PjUUzS34Ckm5/sn8M81S6xeEdPJajxx5SHebUHnu6TprH/aYtth/SdDSocN7kI7DMdHbU55KTox3GD2sV6GtnaLuGtuyaLLvZFRGruYTBi0seTDwD6gn+XX6TlTG0YgPTYwA3YvfGYfg6Wvljuy0I1hfiqoApxo6Gdmv6thvvL2UfjNhRdd8uSd7Q1Sj1V+YCv7Va1KGDTbJq/Y5vUaYYKLb+VbA1Vr0oPhdvt7TzebWpHwyuxKFUojKlSwBSDBOQ=
  template:
    metadata:
      creationTimestamp: null
      name: slack-webhook
      namespace: observability
    type: Opaque
