apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: broker
  namespace: rrq
spec:
  replicas: 2
  resources:
    requests: { cpu: "2", memory: 4Gi }
    limits: { cpu: "4", memory: 8Gi }
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: merchants-db
  namespace: rrq
spec:
  instances: 3
  storage:
    size: 50Gi
  resources:
    requests: { cpu: "4", memory: 8Gi }
    limits: { cpu: "8", memory: 16Gi }
  postgresql:
    parameters:
      max_connections: "239"
      shared_buffers: "4GB"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: shard-a
  namespace: rrq
spec:
  instances: 3
  resources:
    requests: { cpu: "4", memory: 8Gi }
    limits: { cpu: "8", memory: 16Gi }
  storage:
    size: 50Gi
  postgresql:
    parameters:
      max_connections: "239"
      shared_buffers: "4GB"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: shard-b
  namespace: rrq
spec:
  instances: 3
  storage:
    size: 10Gi
  resources:
    requests: { cpu: "4", memory: 8Gi }
    limits: { cpu: "8", memory: 16Gi }
  postgresql:
    parameters:
      max_connections: "239"
      shared_buffers: "4GB"
