apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: platform-autoinstrumentation
  namespace: observability
spec:
  exporter:
    endpoint: http://agent-collector.observability.svc.cluster.local:4318 # Sends auto-instrumented OTLP telemetry to agent daemonset
  propagators:
    - tracecontext # W3C Trace Context standard for cross-service distributed tracing
    - baggage
  go:
    image: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:v0.24.0
