apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/platform/datastores
  - secrets.yaml
patches:
  - path: patches/image-pull-policy.yaml
  - path: patches/scale-local.yaml
  - path: patches/kafka-config.yaml
images:
  - name: rrq/migrate
    newName: ghcr.io/joel-ajayi/migrate
    newTag: 183c9f30ceb60c3e0d569e958b97ff2bf933ce5e
  - name: rrq/seed-performance
    newName: ghcr.io/joel-ajayi/seed-performance
    newTag: 183c9f30ceb60c3e0d569e958b97ff2bf933ce5e
