---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: redis
spec:
  encryptedData:
    redis-password: AgBCRGGsF59OlDIDQ5QkDH0eQtU4aiojSRgBMObBoKwzEwVfM6hnbIec+MZ/FIz5/clbV1B49EAtbuKR4m7LX4Uges3s6j1h3yD6Jstue4djaLn0in8F+b5uW0n9dHaiiySHBX0xyYFpGXp/ldG+XjqIoy6r32pfrBVgqoFn8/dmWlwvZgvkQt0LKI5AGH/JOTQrQGLKgCzgQzr3kR3pA5FG3y3u4SYKqi7IPLG8zsc00hlH0dOECvhoIkwvezAn+CaTqRQChaShfiMg6hh0R0LlbXK2+3tUnzPO70OrRaS65nGWRVUa04AK9klAP1/uVB4epEp1dlkHnJHqFa1KCeGX1jjYVXEUfc+s3xjxuJZjkbr+UhuE/0sRGvv9TAmtxx9u6XKElcdnuJAK9wchLvCja3DBk0WcWZS4SRVzDbddyAOutgsCjrsQtV94YFLHwm+iWQnbyycLoU8LtXYS1k9d3g92wQbnOZ70qPnW+Roil+lQ4lM9xplWRLBW4prqxlhPYGdj9qK2g4QIqRzzslv7ZxeDJLUujPhNOxiW09ZvC6DxM5+1nWWinKnR1Jj50ThontqwjyFRhpK5kRHDu6GaSEAltFVSIweA7e6LRcHwURsstOycgegcupg/P1fLNonNpR3sFD0rGnD5htuRsMXUPfoIdYxUqjlWgj/UOnldILxozIy+ofsSC9yNRJB/orixNsG/4VXUsNzIlaSO5w+jwC24b2WNDc1Hr9qraT5cnw==
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: redis
    type: Opaque
