---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: rrq
spec:
  encryptedData:
    redis-password: AgBrWFHBtZ5ebQoEBqXBC+QSbX4qxiHBbfqHTVPkyTsS0Sxnn3ArbS+6tmh3a5I3tYw72lPHJMvKABc3hsUoQOMKy5ur7yf8Hsya+Juc/FOvwyUIuGqkti5wEE59h8MZZVvm011D8kTXtaWnjxhkWMJ/7TuQfryepsxM0yNRlBAx1Ji6z5oJXQ8iTlc+U8/v0JMma/GUeYxalnGxP5IXCt9LXTQT1QqkEd7QhxoCY4JpPZCAH62ts/c9OPbLwx4yyQ+Ey31KActLB1K5aJWHQu/eyU+4SkmSqGuDkvuWELuUid/qO0clGm8k5AMr+GzuL8PT51AfIrePT9n6FNX83mvkW5PWzd+o+NJutd4iPhy6pkHbIecUHpCRcL1PrFJJKBkfzCmVmckCMpXjvtfZN3Bl7u60ZEWfRNHMraItho2+Un2rJ5375t0hMLRDwdz9T0snU26FuibvskVUyFFJ7ykH0SM4GJ9BCOBsbNuD+5ZFnt5N12kI2eq24bwD+txNphSPPWsgxVMjVYaOi2K9ZuZXMO7ZJ3sUJ71C5S+G42uUBZbLV71cNkOoNHZTUlRrDXxgYcl3S/CKkwtbyl/ZugEnK0e8IkZNmb5dZyeM/yD4bQGIYNLm1GhZS4h+k+BbZcFFtn7+13FmI9rlKuitL7Apl8hFMICceroCDLShGqzCkx7MJXhbBOClyz7spQQpCmtbiRZi8wOf5du9qVgwwgcKS/OsnicZ1oVbTQJayrQ0dw==
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: rrq
    type: Opaque
