---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: redis
spec:
  encryptedData:
    redis-password: AgCdiXiLOV7iq2VB/Qr8RFenX9eflQvFvVbXVkDpGFEMJxfYS1lmYAVj4H+re6i4cIi4mWM8cpzJ4jzWndywrdrcuO4wo4St3olUZ/vVs0SE9HfZletLJrOYqEJH+B9D3im73Mfl5n9HANSshGeEfYcWKW98va5zPyernATipSuDOOBDZ2Ftfol/m0bzoGgzNNT3kQxbU2YZnwhO9aIZSdGNWN5hoOnRioeQPazTCWLUyNZ7gnjASN152myPOy+eK/kP3ujlVjJa4CR6QoxUIWmcUvmsgPwLu6N9Ugp84J3EFfLa9CXzF37M1gM5T3u0u6YzNJB92N+00FSu7FIbOFHq7mIcBnV1rpAwVbRqAKq5Hssk7nJgTulNn6Kt+nYbNhckxsRyyExhkkGspqe9bvLGFnrgjWa/w6EYz+pvWttVMNzb8iqJfrWFDCuh7BkbR5psNbw0IuWHS+GH4bkDbZpcHpOiCe7/yAH6KVMmnVjgTIlu+tvaYlq7tqG4JO8/Cx7aKfcUGpL5eoyuwqirvjTVuK8O7EcltH+vfmpN4ZK53K0KVnJ5fWDFGHkZvVrjnCTbV1SeXaPPsia0GJeSLzmkrYjXAa4+QSh/KJRvjEAYfKTfSiHMqnkmrldEOEASlFCt+JRY66Y7nE/y4Hwyih3W6g5yzf2Qf4gIa4/Tfh1sLF8cvBkEpIb8fehknbOoORcsE9/EXedCXNVo8QHTaOyCgCc1ioEDZKGPZHc8sviW8g==
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: redis
    type: Opaque
