---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-webhook
  namespace: observability
spec:
  encryptedData:
    url-critical: AgA8iE/LE1REes9Gx1nMNz1TK6L5+alcK7zK4yx7Fw0AOiwHXGUOqeaZMWA0kqBCtNTx1GALy70iUss7YQpAYs7JJupRdeaVWGWsT8sJIgeoMG2a0qApkCKV4mLGM+9iFBUllSfomijF6KB0LPQjVSkCWE/4SnboSXk5rLv2bIiJ1HUimXByIVyOv11nCRtEueZnapLifjEIsv/KsOc32A5rYFYH4BuBDBcKE/sIUQ5/sSPx2pyJMvb9TmTBJGAOPoBKkseoHYKCoJyhBBth2bKAK2AQrNxhI/M6iqUTbtL7AAm1ZqF6W2Wi2iXi3RFifsfZE3+h+WVVChZF+T9aVnsJ4WLzM7+EtRMPR7PvoUE+YAYzHCtET3fbchtregZM6Y57jfWL+/yKQe4+2giLsfI3LfBCLeO3VgxIA3xHSx1wnIycIhN4YPsk//hVveoPboeCDnC/JRWbVLsI5ws+1Lz2L6GjWeGIx2WJWgk4Lw5UVKBvUejFQkWvlJW0cyD44SYt7u/YymiqApic41ioCtumSS9RNvoBNL/zEp2OTuQeCoO4AinIQ7ZUnsfZHpD+H2nNgDDULObp1hGUNjBuKntMpWTumKDQTOUFWXzRlW6I/UvFLaEDT71gP6PVS/AN1bXZkRgGnMrLMHVTLg+WLuEdVcn5HgS9OD7F5aOlgyP/lK2qApzkeDXtlfmYwrt6Oi6nnEksUB4PRIuOsu+e1HbZtSSvIkSIQaAQg00CBKl7nMGVa9OnbrA2UMQTFz1qdvaXGnU4TuAjU1uQ2TnrC01DHiIsklsRdZ4zs1NEDH1YLtE=
    url-warning: AgApvhaU4aeQrH4VjYP18CLgNx9GHyziRR3aD3RhXPRN9G1FMUcECF01zBq+yxuUu3n1mx72huSI6CI0sBPOLYNiomeIBgwwHpQQ8rZc7z7RrJGBKVFNWrs+ydX+PEIsTPHFzQVDQWmDPBWLGaWblY7esad39w0ati/MN0NNpKKaHTZpUtC2hg8yPMGlCBRUEkqbJxeBJpLvGM4f2WOqYLZT4vcfwQb9eHMegqukQvm39kLtvYSO+Y11jMiLh9uRuqvVEwrYdjcBIKRhTtPnIp6vxa/lMP0A7rVkJcq0CoWwHk8bJGgieJoGS4yS9PqgVFT+y3Oyu0YrL1/OBW+AUkcXAD/gkbEf5Jx35QR9bAhrM9E0spzpkZnKLSNRno/7hnjOMxy81PPPL0ZxNiZD8Cvpr2Lu8DDsNTYI5vTYB9Cm2bJoygMyoCptPWfRwHdlK9s5FRw4eHt3TPoLT2/zEmNsVqAi6b76Yf3BeiM83CXJ34+cXB48VrSNEWonnE5FPoh0U8xmPv0jubvMjtdSnGUh1coK5xpO35upHHPQ6wWMwcJOVyCcV5Ak1izwpADWfyXoJ+7YRfO5DGR2oe+Jq4xMkenM2ZE3zzT+M/dL8Ge2CH84rvW+hheKqsXkVfklzvXFHzhhyvZNociNM0oQTppvH1CO0w5PxYCW1cnUC2Pr9LgEmjigIGRTaavCyHfJXAiBUE7cDJUdUn7Bpxi6eMcTJXBlehX+TMLrrwUiFCNr76OSst3vFQ4Db1bU06jPVWGTYPVFYHtu6Z3PCVQzK0+W933C5ehukukF3OKmphdy/0A=
  template:
    metadata:
      creationTimestamp: null
      name: slack-webhook
      namespace: observability
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: observability
spec:
  encryptedData:
    admin-password: AgAtP5a8qrUtj9Qo8j0TJb10AB2XsTOn0AY5kw9f3BiYVF4FI2sknOo1t9wIFcNdLt8uonU9QMf9XfjxKP48+5ZL552YfETEnWteCFExwqns0ELOWRtIasV6fgXzrLAc7QliC6OJeN5IWjINdEX8Ko1hY1XGDgcV5/+NlcdvQ1zCqPMV1MG7XzbQWbX6MD5UArmxz+svFmKsfj1rh0knGlKlssAJqr8vgXTjm7XLJFqGJBQZL4AC84tyPk1dzTxEjYIdxEFxBrdyg7WVxNtMAujx1xwMRDkWI5qtY6m6gtJ4FcjZvZXONilv8DcU5f3EuS6t9QUrtIf0Ey31mHVAcGmwfUwKWgStDm30piOclBHT30lyViUBjkAjyA/ZnNdUPEY5Lfy0XV6aWaXi0cFAlXkZzFmwX4CEuHjhDFtECLFGWRCHzZCcHc7Tkl6RhBJgtxw6XzVEUqHrb8iekE6xWtkJs3uXgpL3WuwMvJSXdXzGxmL+dkzq2uYq9AuAY6iY53NeFTnkfH5DGgciLoO4xnB3aa/0aXUQbcmLSdsqn9IS/MHXvQFwvNbTPXL8+FN/SvTRmasHGWl3ci38lfxYefhHRLsCN18jnkJ3QPAkZp0DGx0XqZ2hLGxbGxFoSgiql8xY/GvkB2RS0JqAb8oO3HZ0rHDOyZNtokIk/uFf5gnCk4gvVuVqjaQuLZJRlDuSOoXPfpktblNh3d9hEBn6+sl8CbrC7PzxwWMyvyKxwa0gtA==
    admin-user: AgBKPvDAn6eok7dQ+ntrRGXHVat5ndo+klWEqwZQGhifYehOUC9ZMdWqrCklfbyBO8MNZHZECWOxsxU9iK3GLqIa4b05RQrjfKRg0jZEw4fEajkqq4t6CIPM/oGfmVtQhsyo/c0/cZgfffyKEz/Fu14SyAs0kmmibtaT+z3MirnsBsyxDi+m5vBruLMzyeXZVnOZ9Ei2EnHDckTYJDriSdUpRZEO/6tqbqz9tsJpH553WD0y0B74Ic0o+kkiPVT3fAJoBn9mW5o1iZSF/d+Lw77KPEarxVZfLkSLiDuJK60DHEBGGhfP2Bzn+uC08+unSNek2eJ4D+U/uivB3Ofk0xKXVAWtEmKlyOah0CHoolKPBvuLOI6M+kbqrx93bF7z7j3SgWDM64fNzp94yJaJcSfhT4YhGKxyAMdr2sGwNeLKdUYZUUDYRMKvP3EH37Cijb/Nt7iWHiN2UuWQ3nYFmzbr72A5/HeuOwn6cEDQcBydKAzzmjd8dnLg4tgVPI2qFHcPac2rPGpPyxp446VRoiOkwHagdDRsT2p7gAGWe3RxeQ03Mshbjcmj3D3Od9ivnp2lgUkiaoZAieboe2/6IrkY3LO8iPv9GR9hl9Jttb/C+2Mztj6kUSl5K6uaRywCR4twJRS92V75CUrNIHAuzzFO4vwHaKrf7g8c3Q6bnPzhqjU/+TMy4SYm+4lKVjpizPE5xu0nmg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: observability
    type: Opaque
