---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-webhook
  namespace: observability
spec:
  encryptedData:
    url-critical: AgBSFGDlsm3DGXUn7MwhpeAPrCRHPNdI0uTpW1RMkUboxXhcracQ+srCrdLJuKrQLwAbUayZi51TCspFld5GebPHaooLbWHCH5hlwR8Kt8PgoG7siCbp/Rg84NinPWZ2KMVOWJaT/GDy1MnsEOPbTdOhFGQrVM6+IyTibAcgwWnQTj5eUZ72xkK4nEWKWGYBZFJm2qbKJsBT1U3aQcB0UTx0M+5snw9Nwrm27N0Zs9ESfXdTXS1q/pqVeneRWR3QJKtoEOj9mwcnzmsbrEs+J5tj+IPOD7V9QihWe/75FUMi/vFoMj8rrJFsBRWmR20/FMx1Amqpuw5ObjoIoCC169nUH6oNcG5g2KrCke0qJ/STuVVRcZde8qDO8JQX55e9tlYwmjUjWZu1xNvN4HPfxmUIRniZyMJM0laKKDK/LU8sJCQ/vX34uLxqYi5QXellvhjk1afyWCiro+9/pcG1D1tjT/hwX1yDHXQ4HND1BiZQp72Xif9jf5IBPSIYS/5uG9sO8idFXS7s53Z0NqleL0Bt24O09aVEA2hi85AWvn/NIThhOyh14gO6BfMhlQnu4TmGbNlwFlqgTSKhTie42XjeYY77obyoxS4w0pY3AOiBVhv7ru/2vHzWIcsPSpFW9FtYvMZg8F6th26AyiTzELZ5dVTrKE0OqkwOCOQDCVz6l4SYkAfnjuwKFS4qs2shqr91nF0iQkHcHSX/OJbCGWSogZiApteL2orA5mYEg8nHft89zk0qtH9gv9CsdYcw0Pkik8Nvzlsn3Z6J1Vw7Ori38E4AFET5OFCJ1LK7dOh1KX8=
    url-warning: AgBvAK0awcOyOhLS7FJVKgUuW1Wp4daCHwZUN6OZpd91RCcWJzc0r6AY2Uhe5GtBu6YqOVK2Nb0vHyoP/Fc3rbN3okBpjwC0vyOk9PBNOhxO7NAACfM8cN4b+PJ1eGz2gqZZwcMNYm200VMMn/7ElmQfzNMYa5TXhIJz+hLBbg73FqgTCp6KUtXbaQVnpPeIxAdBvWP7+17tpRADUBliemglyETcKf2qq3tVeiJd0z1Os8LYqW8zBeFEcp4AXFGztVL6LpgN3QjGqD+lzzAne26kU4PU5MBir9VeGocnbwykFkfvj5S720JyBx0s73wKlL3um+N4WbtXXQ1UxvtRWZqz5H1dfdPtTQZQDPLk9g+gTp5jSjjqnjWo2LUh4Ps0Nnd4EFqzF4pi1pHAeSs5lGr9I1WJPfJIUkDYtbtFEqo0m4WButbmudo/eYtNHEY2DeR/DUQPC5+030CfXbLU4u953TZo9I0CyDzpJSQT6wctIfdfUhRxi2SuqQKD916FvCV/3Nsaq+9Rr0XeWxxsLtRQEf+dM2XV7JDN2/4JkRT8Efl8dbgQNRwRFv0uDR7CRyJDyOd4AHujJIBVJ/muHMzrfsWGumlmoxjuHVyQ4HoomhuJfCtRadVp/2lPARMK7XSqXLMFE0EaG6bi3aSL3BCnAucYLPCXM9xMf5BeYLTpXj2tUOG6CN+rw7J3Yg/gQN/RnAJtP69jmYfEyRU2H+agHMoRJlANFtk5bNf1FHMXrGi0r1bYCYVtNdoL2uCWNE7KJObe4X7rexL3lQ8kzqQ1Xao5DPkdLuSFl5j7e+SWdAU=
  template:
    metadata:
      creationTimestamp: null
      name: slack-webhook
      namespace: observability
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: observability
spec:
  encryptedData:
    admin-password: AgCGkkGRf6isxhC5rpxEmiAsD5Rc9WwlIB+wwmle2paJ/Rl8/lhvxzjfBO9hsemX4F91owvQu3ImSZeMhi5mowbBB1zANCwCASaGnqnBPfMa+yZDkaK05lIlTQhJr7sbvWDV3c5z6wkF5Ub/L7mWxfV6NhGsD86yb1G5Fiqz821dYJB1MNh43efCaa+raT5RoIk8d0+jhUN0gg/nn/xGUrHUp+dqCPpOdqhOrqpiBZhWHD57Gs4JQZoHZH495s+DaG4vBgFtwtzxvCChP9HBT8EeMRpQfeJ3Sy6C/TKzKIhrcsdVtLhzT4ubTSlnIO2iNL3W9wJD46KImeFuLVTZbFnIVAyCShaDzCppP7n0GinBstxKLU/ZXqAcxOYGrXsoLs9toSJQZzijy4tFFqnC5b5UMHg1S5JdwXBEUwzoj3fTzgNkR9yhh+ZTi9n8hkTRwEWOY2Io2CS1QCEcr+pqyf/FCg0coyPPLQpRD3MnWtIyghEndCSUdvjmbYwmMvfizduwLmLoxbDH1RBcTsgczV9UgdqHaNL7D0GRZSDVucePfT4vkqkbnOaPKss0XAfAvrY+8AM8kIvHvErLO+6UVHdLiR6rwLfB/6/xA5XKag7I2au2IZdop/NkQutilwNJp+LC0kzDauEdio0+PImSIBIqH19cnStnk5Pq/6TNgfoOY7LvL4E07IMNMnLJDmmZwq09g3riURQzM2Kn/4IqclSCxcrsBjYNVCVJ9C50EqFNpA==
    admin-user: AgBMka9RHKImJCF3szl6R9ZH/lldJ6Osk96gYHlEI1Zt5aPyBvy1//xwpQN+ntJ9tmHZzVNQn7nl60U5eSnLUvqc5b/2FPa/wQrBcleuX3MhVpNHlmes+puF4Gb7VH3exO6SDso95muup6dsVZf0ugCP97zs7IZetmcraBR2ECUL4gIKX7TY7fzOaCbmXR6Uaq05IUn0p7k0WfBEGNclHkmBmGx4UU/z+CGlzGSYP/KvoZwCKRsiGBOU6UOQs1ndee1oyQV3eQlbEhIJYb2tb29rIRfa/g0fx7mHtKI7xI1zIxjW7XmNO4Iyt6cRKocO1hOCCKCfpvLlmYoxefHBu1lDuHcee131p/5kpt3gQzH+A8xGldcDz6rUeYutCXiv+Wr3stYsYeBDgmYKO9ipGjPTGM2F2pZYGr/DW34UoiFmLPnsrSVcjc6lMG5NG5LdJYEfpb/tmb9MKR6k/vH77YOdUNG6l3QAhPGPtGyNbMINA4GqAd3VK7jn3DdH6+zH7qyaaNcfmYHPp8IP8gTRsC9vmN+i0zh9/2YYwm+6k83PVzLzNdd9Kbutue4u8AEzCMBdT+xsLsMjZs+TQDqZSEqrJN9L3MhyLayfw9cHxrVcnc1Ac7M97wy0fB7Q14Q9FztDT3Xvy3Du4+pD544AW+hXIAZHNnKYbiSdoUk26cbx/ebYKt61KF+0y2leoMp68zrb9k0QYw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: observability
    type: Opaque
