---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rrq-secrets
  namespace: rrq
spec:
  encryptedData:
    JWT_SIGNING_KEY: AgCJrqlHsOsvvtJnPOKXBTNPuRTWrCuI9Oqd/HO2HXeesEDyuM2lkBfa2qBPtrIrWyUhqhOfVubBSKFNlCF7/fCkNGtXjVjM/nvCaGdZGNdE0WfNhB1BR5cE16RN+bn3XgL2XE+wxi6D4IyBcUOk6UYHAK/F0T/TBEcbuBdZOv4hgkciWX08AIFwceLtjh/1iAqUfKKvTMp8n+gXm8tPS+y0CQDzedsoDS937qQ7yXFhBH+Fm+DlCkACQUuzYeunIfmeaWBdmZ99nXwabJExXbgulwdhSdKUgM0iOq/IQhqCDlyOJnRmlxpWC5+fS0g6hZ61nTGr/THF2CsRabsxDXPICRrgzvkgnhFrvXY9amJe8xHQFj2FaOcCe8EBk9ciR+7RcIEXFmbZkUYJBLlhnkhT39jo1T7MK0x5EdAf1KRStdpL12KaQh82/jP6v/GYaEvQRhBtUYz78nnKWPI7rl0gBTCDwkyzOolKxM+ozaNYq9GzSodnVZDL9SlRFA9XSDnURcpIk/DX3nfYjQlkMlfBjUu7Sf8fVCGmNS1e5EDej1q2Hr0OfkQHX9EYQ58M9/tHMrcFVqFi/gssnK/yN0aXTolmEoSfvbsWZM9PyLidNsUc8erxX7+iz0QGPyQGwhJbsxnX3sXJzzhYuoWenrfzLfIP2/RoVRtcYvWcmbHA1knUKwqRJNUVBdLrYyQ6GW4MkQ+WtOrrmL2Bkm41XK1hGgtHbnt1oUv/CDaMB/DmGbBiybFlfaarV1/RYxbZssTQCHTXLMI21Aud2tk7Ub5PZKJXTt3bv/tkO1QNxZbZvrWZu9eFx9bDavrGB9b1
  template:
    metadata:
      creationTimestamp: null
      name: rrq-secrets
      namespace: rrq
    type: Opaque
