apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Joel-Ajayi/rrq-gitops.git
    targetRevision: HEAD
    path: overlays/prod/observability
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Force=true
  ignoreDifferences:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jsonPointers:
        - /status
    - group: opentelemetry.io
      kind: OpenTelemetryCollector
      jsonPointers:
        - /status
    - group: elasticsearch.k8s.elastic.co
      kind: Elasticsearch
      jsonPointers:
        - /status
