---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-webhook
  namespace: observability
spec:
  encryptedData:
    url-critical: AgBc3Uml/ihW6O9FduNgG1PJyKK32FSY/xFHsDheXSuOYppAb9ES9H6nVzUqBzQWF6WAMW3JGPzExUDuqPacADRsyIzUqJ7l0VJM0X5SEftj/Snhyx3dQJ8TcO67EUFRDfPPp0hCOJy2QdcnMj17mhX4pAuXAnA0fWdxoZiIdIVH6HdXRFjjYL8vS8uBpl/0xiZ5Ervl0vIayux9uNXHv/DbjX3S6tokFvpJpMco60b720HGu2Pkzk8om2u76x0Rqkp8aJdYsCpmtw5X7EI02g8APMQ0OKsyrUaoBWwKrcb1U5zlPTemXiejrF8KaxfCsdI8ULxIr8ERjgcwD354GoqL4dCNQYqlOef05XGIk2xY9mz5+vOHgFyihX9KXcUgq9YERDMisICI5WXHzfL4XhRD3lgagNaTGMRO/UZVlNpnzCR8sOJ6fdC2lxREryktXQRpihQCJUvREbzyo8opIkxQ/T6oJM2Ud68tkiC1gixwk2Znq1s+WE1QUvgOE1JtfRLrztgVMpKFhIRKQQV2uI1oHyr/LIlR9yUYECUfSAt4LJgrauqLPqYZ0kR5tShOyZmAHL4N4kvhKzYTIExJApYCZVtwGJFEFR/M8W7FtVC8e7cGz0U1gIrpDh4qaFhU0nEAYo3B4DWrmh03dCIBYr9LBoZd/WAHqDKcl4vbsKs1PON5dMGWUBp+AOiu/b3DsUBMeXiK8hkzv8vWxWUOAXwd2lmmPgt2hYbsCKpgXXQctdoL1j7ip4/RcTWEYzWeCyGJceX0gBne7OvUApOWi17cwZIV9TbiGNYRpNu/hTAj1aE=
    url-warning: AgAGia6w0J+5xz+WVYOGws1W7cEOGo/fhFKXzOaf9+0r8b+ds4l7RDZ/KI3XUVea3tHvILYAmLieMPEiBfWzw5TMCt5hQzM19IzOy3HDV93EByKQ0Z1US50UW8DLj3VVig1WH3Lt2nCJ4T/e3rHedaJBvcQmKNwQ/KcNRVQ9MBpcLsDRrN6Nfmi+SbANp8EcLs00a3GKROWdEpNBcFIqiyXohFW2Qg/HPNMkvSRbcDTGenk1KtUptZJ0LD0++6LnyTEY726ShZvq8JQmoNPfgJNscs57vX0VdyArxcC7mgASPC0OgaVw6aE9eeiG4x/3vn5gta2svIkYi6n+DD6vs3mOZNdlA7ICUy0B19kScNGaTaVFs5eRcJQeHzTubxsEk6ItBERfuBvEF0nZPf9pGXRvtPEaXyPIFGEKf6mIcAdsuLGsgNCkht0fW7y69Vguk0+7ykqbZbFmyllR9ecoY65nOPytBzyJ6BTRWvPDG8lAUcwYe6BGHmjmezjb/C4jkmvw3kX/NAXYDdIJPjZcq27AttdXOpZPcxGoSxqJmRW913t13erD0qsrI4DATvCt2XSqlTPUC84/Tr8VOeoeoF9rzIEsqdnkI+y841lWzmiuMb8kbwpRCiv7s2I+25QhsD9kAS2Gm9d3pxEWyOuvI2t46dWudLhS04nntpdjysYwZuw3YYI5bG39fHcXgIH5jN4cdWrGuWgAR7qYRZkbTorTnLIYpf3W7d6OSlQk7Uz5HimFjYHBkxNiO4plWSUiUGoIgKP9F4T8Tp4zp+LOpgXxpmI6wOgjbQZRvm6mwgr5sxg=
  template:
    metadata:
      creationTimestamp: null
      name: slack-webhook
      namespace: observability
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: elasticsearch-es-elastic-user
  namespace: observability
spec:
  encryptedData:
    elastic: AgBmmS3iEsNQbULNmf1jHL1nfw4gqViH2eBsZtHYGAWWMpgbzNLj+nzXG4AbdztTuLUHmbjf5qKFwwrRTjL2m4qZgW7Duhup97YOmPpgyxHKCsn3AOilKyF/nOYoJMnH+AdCDbPGmVa316T6DP9cpfhSIUbrBBPyp12fW+A3dBm2vjdhTCRKy+oPKVMMSOzZoVsPO0Qff3RcqY9/LiyBsb0ehJzfJvSvxVxypvxKFmhYwuaofxeFVZq7/84IFYDSBa5ub9GJoMIAb90b67nmajIHJLHoOZJUA/e3UPdziPgSniFC+Wd+wK1Zm6VocPelec0s4Nv4pQMYseSGdjORAuC2/aq5Nb40kQjOvk3x97csdsSMXDsIKZ0hdoSBHY9hGYBHa69QylZUUV7RUybSYaFDSUmcNgFX1MGhvjKv7mlTbrmTE0DWzDYdIjRBZfvM+5VwAm3iTSED8GGgxMrFS5xstqJHThkbV2RxIIvl5JGQV07rgax3x3iCT+mupIdeZxSZk4PVcvVdR9OfovYLQ5V6G4RKoUFfe24ioG/ed1We8VAI6qHzbHhNN7sdy4x+oHy8hqZd1KG4A/GnSGxHSUN1MhWNxz60ijXal4PryU2OHIUo1HbJGKFS/+7FkoPFkrJ2555s8C+SGAjy6GmL2bjiKLFxblFrLewObsjEeeq0wvfW14rOpJHapw/Oc/vgjbWbbDRchKg0KNrJWDq7cR78iMEv+2whWkRy/MdFTaIGe98=
  template:
    metadata:
      creationTimestamp: null
      name: elasticsearch-es-elastic-user
      namespace: observability
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: observability
spec:
  encryptedData:
    admin-password: AgAZ+Vob1/PKi94SN4cCQxmD4vTHqk2+J8B624jyY4NTzrUUyX/cRBLaAvH5caHdxLUIh9Fu4XJYleiyqQJ3DVVJ04mKgkjhZbkG3tzGjvkVu6ORENOGZzy0NqVOqYGPXYyCfgRc6qO+brlcRVpMY/NQh8YTmIa6Bn13qVNMkvqnGOY1iNOWl9hqu+0MvvjRByyO0QmpXqHgkZk/xWHtmKm6daT77znbrTelKzRpfDn1/qbIytWyp2utMGkcw89R8+k37z8xe3PUormIoht5zmUNNW7MpDYnIhIGi1QP1YIiTzfuOX0qR7wR8aKWW4kpOKnlS8dVjS2iX/RyaiCt58YwKxMwJlHLFDL/7N3aQe+TMGEMe5qxMKVNDHSZrzb6iTxzkFlX5a3Fk1Vv0t/Q/4CGfCdQmBrhq01OlAHDtJGsPBsmJnmTZ4tYyFWiE3ct5dohTWYzaJfh1lH5+IpUtFhs3L2gEvFSSeWOXhUtRSGplM5KzsI6CKMmaUULfiN2WgIR30Qynjzd4I8dnwKjrU6w5alm1r5KilIdmpWoo/SbdywF3RZza+gpCrA5XW7Ast+3tSxbWJoOb6O1ahvI2EKOickpINy4IpP7gSM+dJ8ZF43yM/7n7NEGwn8Ll3poL7tbs6INeZHuJjH7ulwPFyMndgpY/W6IaBCzmbOUeeQtoQ+R+3kiS3EJIGgTImMpwp2Gxo9Oi6mqi6AUk/Dg6SEW3E2cJixAyYFq2p03I+hDCgc=
    admin-user: AgA9BHSmc+4s2Y8KACSnOmKkqTJ+3uiExHk75MCObgcaZ2zF39Uk47d60v7bk/yjVAIIMFLJeZzqusLm/tpWKfSaqA7zqfyDNok0hd0BUo9NCeIAfbe4th3jD5ORaOSnKy8z3wKnw7gfENx702iVKUzfKyEzknWN/mUhUTb4fTF3wlY+BoE3EFEhNui7KB1fekRdH/yrlkbxz0/sPzU3/ypZw00m2gtfO+hjqIDfIAjfjqB0klFCRV9i7CBnjyF2mNf9Pd6LYsDng+bw18Kbhr5qWQWuZyqUUd5dTQo9y0nOhAmAzBC4jCNGYZ9D9MbC3uhCt+Pd0cBimjPFxzeOZ6vvk41i8wDzAIdNHBZp+EVPwF8aYTq+9dMD1DE2V05kT3FgefOK0O8vKZUpVE+johnFpm/suqdaSFwhJF2n6jl+JO5qlGZJ14vcqwOXoFSJkRfNnG0IUcutXOHRQU2g+rlfV9rJeP4wtlnUoETPvEJRjX/WzutO8w3i/C5vgYdai/ncmwJZeTg+c50FvUCILb6l3l2yjN40QuDSXOvdd729/Q40gPYAFKYkA/AGnqC0ivBv8m52YRdqBrxEW4LPA4hLdn3YqNPGIqyVqsf2Ag7topgqgJo8AjBC+Mj7BLFzxhJa0WWC5+rX0IERWtZ2iErJvxsxmC6hNz9vtF3i7zi664jQSL5ibtDeLab7FrmeiTENPG8VZQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: observability
    type: Opaque
