---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-webhook
  namespace: observability
spec:
  encryptedData:
    url-critical: AgA9g8tyicQelkOeHiUkU8Y1wA6BxiZb4q3J2PYmn3N1RR5+bmzxewYRqpf2bkrvlZyE4FWsOWh6rxmT0Wa6amEKLTzu848LGwCruoMLC8rw0S+oZsLnlU2z7Otyw3jlIR7Eq/kXNl1sTQib64C2PyKAe6ApbsMH0fl1q44daDbZoswuEAL/UTdiybsJ6LvThhAQtKRysSfDMgMzJwnaxUu+wIVDqIViBZds19tzuWUbn32C8b1WCJA+WuLGAiyjR2TJ7MUTamlJcf1Ioms+DOhMa+LeUJq+dGH8vAXVkuC7oxqwDnBHMunEG4R4KAbOyNz3sX8INzqh1W8b3EOdROx3PSOyJW8xM9SG5CJvH+RK04COuwgMu155yM4lBDZsT5ovXYiGJqWjRjtTgsa6gW6z/BDSzUfK4tJtjs4fc3515kACxKYtVIbEJVF476NH1Dz0Bx0xQw7Hh/Z4LT68OE8HIB6rRBnE9UVxIjMmI3bZOua2utwxpoYo/nPYjQtRc8dlT4bRrJboUMt4A5pQ21pBfPuoLG2UDTqOtWWN0XqMeNi/zBug9ksFeyfNR06FynsVxIJEyboUbiPpjAbut5eszhCgGtKoR7anTghIqeArGZGfagtMaVCauVoOuegVupFk1uTYOrkHo0/L8K7z3fa6j4iw1SzfGPC9M8AWAK2U15my6H5IFD3cXWXgW64QkzXWN9ASeiT22f3jq8FTEs1MyCTrPhJE3H5O6NMvWs/a62mqQtFqsAkg4OKo5/+1+ki4QgHP9/YKYKVwnt/GhgCKbVoE3WzLOlSOgqdzE/W/Waw=
    url-warning: AgCuvTmoBQBg14Pm7xyFAHXU7R0ehK21Xp4dTtayoPFpY5RM7qDIcw6ME/clf+jUEVTIexoRzd4O+hLGCw4zrIoQeGGsmNbHl81lKS1AapwrBu2QjRFs+eXZMO7fVBc7b+0bpwqg5++Tfs7V53sVMVVlLKAgC9Im2z5+sQOHNgL8/Zc4pXklKpabjLrrXc/Si+QnNSU8JDNbyrx5bnv9RUzJIH0mOuC9QNra/xqKBQOBPFp85mAjeDV52liZubGJ9Z3iinIiDxwt1fCx7vWwbNfPGQUibynBl2eXfseQ1mFpGaju4owE9jhxf2Ut3uRgJwoPYOqgWdQaJdc2TSvUYoxkgR9pcPCtb4rajuzC6sSLVJ510c/c3etiQ2A/45pqeizf20tBSkeTD1ErwjaqO0AysmvOgebGPs7Z6D2QiqeKgSKjt+VlX7GoUyPbtpYh9IUBEgK1AfNUa8hOsHUefKpJMpCHbYyyTmbfUWATWdDXREn3MzIp5QNRUB5uLkaczlBfWkUUbEky3ObuVUo8dIJLBP3fVuZqMUPJbOTDw3aoImCqG0bmE5hty14mdpIlBPsO0w2801zyQTtMluFhCRnnnN8W2ATmaGS1Zepk4qOWRlaZ2FFIhyB+X6HbVyLCVXTmFXI+FQFvMHONSgSc5/wP59HAEG4amz9akzqIK5H5DTY2u3fA9MwSOb4LX2MPcrvOP/Vx/K4qf6UO8iXfoh/NHmtQYvfJAQrnrOqOHaN/RQTymgIq84XEgzCx8WztADStUvnDp5tbB65vMiypC5Q7HqpJg3fElTw69pl72vmY5Ms=
  template:
    metadata:
      creationTimestamp: null
      name: slack-webhook
      namespace: observability
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: elasticsearch-es-elastic-user
  namespace: observability
spec:
  encryptedData:
    elastic: AgC/8TD0ZUNRV1ORuylbbsVgXc7QHWftUWbNOfKtDjY3nso+fLMWLlRk8ZgGDQJz4BbBufqwbFEJiI9XgmGxO/X2qs8Q9nlt1OAysmZSNVRSmEID22K8A/8n9KThbP5AC9F+WBaZnmnqwVfP5W6dTr/skfSFOztYxkubPXEGLLWritoG8YvrrJ/OtNuataQMekaAoz19jM+VIODcxhD9bLED2UolHkIrUMLZ25pNWComuC382nk4wrs9wkgKGn732MdwQb3fN0SBfCKxDx/EXnIrYq6TMLVCcuzS/FJ/VXiho6Kv7zFXpW8qC9eJ5o8UMDgJ6ulZ5N5huwcUavHi12spOQk3eAqb3YKdrPNELZIrYB0aQSLjbWDdk+TpUjMppdHNbdr7X16ziWeR6I+8LJox0RhRwLpqbtTBTFv4aCL218etzHxV5NjmbqG0KUbF6MoxLXcgzu+I5Dv1xaZ0I128p+Xljs3IIr2KxWkPjnfaqLCTtUG3oQYBT1fFA4jmkZLX/ZBdEf6gyRnUa+tcYQfLh9hnXwv6RFJDo05ySd/i7G520hEcCwOQeS9kc2bhjO58QM11JtCbVRH879ZF3D4m5LZeZWqPRisFB/cqc1XlvtNLB33LJiEHvL6ytVG910UCqbH1pQoOzOd67dzG4Iy7O7187Z/t0ghj1PQfMmlce8KBvZ3/q7ubDaD63DES29kPMQP8r0iX/p09B9hrF3SQhi2MGuXqphsIV0X1YF80sV8=
  template:
    metadata:
      creationTimestamp: null
      name: elasticsearch-es-elastic-user
      namespace: observability
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: observability
spec:
  encryptedData:
    admin-password: AgDWL+m7doyzFWznw5cv3Jh059HkIiuXgV2FqxrTdtFfoCihfHk70Ekk272gLiaYu3yURxGE47r6JASAUKKzOxjXTQXsxTf3VfJUk+4Jv1sYn45lGW0aZpseUK0lKte5SYh9Z2UrLpm1fX+45+SSuwglxC4mfgpxzdupacqb++KdNvqMpHWlnR4yxf99hFPgGj1/9VZqBbqhA4sRvgDhKSUscqpn5j8FL5E97hZOByRdmgHP0U/zHszhz9ytPokyCunK+5XDifqoSLt2yRqa3Yjz8QHipqad5u7kYNa6SmJLSFG7OkVEdlDYUV26a9uhga623TZTjLeluStC7pYPtQoWCuxLVNca9hoonf2tFwORuDPjWyGBKz90xgcRaiWCsVmrWPsThoi8cShOYyo+F7Mmax9g09J6waT8bei2a+37BjOmkl6sA4pVAWLPqiIhLYJ1Ph1mBJzownS5NnL3kpRKLVyTyglne3b3UmQqaTglMaXJxbBbxsVe+JAue08L9f5hQyssnOpo7ZFPGW0Xupygrekw9bAs+vhbeesBjv64dEaB3ZE8HUaAVHqRA2CnbUvutklwrRmKMjWIskYbhpie6rx2Mw6Rv1LwdzGt1Ik81ny6XLoWYSlcSYKo/QCoPDoKs1WWOpuoitzk00plC+FzXRgULG5+EzVO1IiIIh6r2ctHZjGKjMd9qK/y2mbbRAmm4YvfaBY7WhzRw3a9Hissl07h+5Iv3h3dthOgcZ3V700=
    admin-user: AgCKDACKKG5a8gzOfWBzriHQoLF/YgX3Q6a7+vRI6xzpzn42kPsxlyiVt0cJTFDA7kN790347zWZKDpoaEfG0Mw3I5NwgQBr4rRAOGlKsjOiNr/NIaurNCI+bGJmVnB+xg/17qioVjLtMJUSnDj7QvBZ2T1YvksIxAef1bsySSdbEaT5q8mdVvjo6R+KivKqKe23O7RODTIqjmxX3Esan10iX9YAnL2hz2sSwDkh9e7LV/dOuNkW2GZ6XF5J5SmjdWPCkxAx0MKvoYHdRydeTRRFj+x2772LaNQmh6MKd99FYWo4nDIynOGeCEhV/1Nbt3AYiTioPzWWXw8lo/62ZSL/2PNyhhUEgMIX4MYRbhPvvqgJMCE8Tm9ayclufTtWtoGAPqH2TfIZwIj5jA7jW8r8ClENbH28Ld9ceveQ4Xx1Njep6CIlH0VTIr9e4BZo1yAVUtRzgB19VG/6eHfOvMYEIW5CdQnaidjyiBFFmbjruj9tLzrcCAJD9uhZVOcejV+McRyEcPhCFgu4S18TJmbD5klOnCh5hORSatbKgDEKpZC1i8EXIP8+meO+QrwH7ykW9xT7SZR46Sj9Edhg3AyRiXvBSUMsM28PnZcSjljtgu2RgJ56Jl32KhO4LNLx0FO+ffGXCLCOb0Aynv1yh4RqJEqbfjLVSYIQ/tUmb42ovqsKehiuQFud84Hic23zmfxP9gmrBw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: observability
    type: Opaque
