---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-webhook
  namespace: observability
spec:
  encryptedData:
    url-critical: AgC6yX2sGmma+4rUVjombI1cpVwAmxlFRBieUqyvV2He7e5NLPlswVVBWVwCFaKQPfq07yBJbEeo4tGhMJaZQg5lT2MaMFxWC/Q5c7RxNkd2kxuCBFq8aVifL8Z4R6faZo4LozpmHMjoVOt9CH3kCic4J9fc1uI7jXsznVvE/P19gZVgUzR6Ei7ZNgcCi6VEBUx0oblniEkSL9QGfZR4iHGX+jh5miGyODyf3nUAL/IKus3u6XFTerIag0kiMCI26HQfW078JN55ezP7sMXpbdlt8EPLUKPSMEQGbRHOZNb4yBoiSEFqaX4rWmmnxNE2Klckzvc+V9MFlaQPFdZhkLLzu2/lrAv/a1CAXs7y6z/gFB1/dO1O+CBE9VrB/jki7+tbHMDfx/PWGzfnne79JlQum0d2dmenp4tyOs6WAPKV/Pe9FqZIpgwalIQpeRdi4hZwJXWXQ5vawBpH1GbfN1Qt0OOnM6N1ODGQMfx4dZDy4fAPit5ls/7Ogt7m5VOY4Xl4ZlNgqGltQZShCs8NO2Dk5mTj7OUzal4sqGNrbD0n0k4zsGnvKDp9K/rlMxC2ES8jYqcRpBSHW472pcJNmN4cdnktGCur2VcPLDN3uLOMfSIKkNkqqGZhviKjLYb84giUfjMWaxiCPcHzRrbRh31kwywr3pkqckB2buVQ2pV7kI442cYZUAo0ExgQKyDnK4tOEtj0qIWCvXOgAdCP843dLBqP12R/ei1PxjzGSNqube1soaXUjJEWyp0w0uJAjIDa5x5ZNzvm2gQm8Zu4Bhr5371FQQmlzNIhSCC1WOYDpM4=
    url-warning: AgAbp0bo8Vw9j8pawu13bz3Oj+gypV65HASmcuCE9PJT9J1Gxzojzp/aZ0XlBSKX9vCKuTu7UxuDekyXAVOKGC7ABYTib2EU7vs14i4no1Y2/HjqCLsCsr8yXvJnd2VKQwvGbpQs5LIlu42sEg5vsU/Z2WnOQBE5iphuu+sBhbZbnrd9lW05XqvI3Hdsdua56SOroAgILGcdFnBcfTzsUbJ8iBRT6gPKabV0QRGZr4iQZlazgx3PhtJTuw9039+MORrG6KIpE9cwQMK3qP9UjsX39I4ZYn+yh1ak2umHgNHv6O7OLTLf3lZ+SUBFfrDRh4U1Dpcp1KMJsyBpFy9bHhtO5T+GhaqRNw3G7xpxRxst0KmkXrS0fzbK7q1fjYXdlkhk4GEueQFFPD0fMp9jh/hfhBCHYWIK1xKCVTxDOGeOfnznAp2Wmkpp4pkjMwOM8+gh5PmVGzF9lr4cWxwErfxEo3gOJRj1eDqVGM9xQNzEzOES8ud/98HF3ky9VgmjItsdDI17Ad1cclXj89/44G6biuTgD+S7SJGvUhqeBcxGpb60DTh6ElkVpMh5nfcfwpj8CE1H6P3BiY0lWs2FqGh6psaG9yIIrVt0WRv9XnC2vmLAxZgz2/g2W/JvCrcq+0D59i6BcgQyTqQFM+n0lYKXE4iQnGSXN7poIXkDFWRjxXAVsEqEqsNZpqWLkSeIGiRYVYimCUNA8NTD6sgdlrpDXRdf2N0BzIIsTiJKTRwKjKGFktNuQ3nQxMcvfLC5WnEjpDSUL6CvG6gihkSSNYutwfSrT70I4J4Be/xtGeyIoa8=
  template:
    metadata:
      creationTimestamp: null
      name: slack-webhook
      namespace: observability
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: elasticsearch-es-elastic-user
  namespace: observability
spec:
  encryptedData:
    elastic: AgB+m46ejZT5FeFYnpRPMg7zm8gr0h8QLNNxKiZPU6FOu9S6fXL8J88Ad8YRG6xGLi4teiaBAa5/0wrekx25JVg0J6Am5V3s5P7srwEtXMMvzQ9b+2jmtiU04daTU+lbJx+vTS9rWf1ZZwaV+V3py2eNgR99pWl9OHcQzcdNA5wO8b4Sn73vhfZLSCy4j+J2o7TL/jx3YqkeBsFbwS4RiWQPKg/jFibparV/DTQ8vVx+D09MzDRt0+d7NFQKZs9xv0xczYk7hQDpURdh5GRSSx+SCUvQte0Keu8Cl6VceL8AyAJYEpIka0HD3bHZy+jYo1tC217mA5Q6p0DC8gSJmjTZ1C2S2q00KC1TccBDy0s0JyPrjDUZhqNp8Qp6llXspSPxSY63rl+OCPVuV50rPKsHJFSnPyYe1wAw9y6kJO/spNKQI8eQBl9Vt0j7KKZw6ezyjxg9V+8RbQzY8kpgSix0nsYBhIBmLy5tM/lBpPwiVafN0TsWbpCNNtBeyB7afJHohhKB/Ct+9Tk/jv6UmFFbv+3mu9oNqiC9wDIFaStpuX0EIBt1pIN8QbuFaqgqJA+ajfLtrKAeOPVR4am0OdMP3MvIStlXUoZuNl7o55WFc+UtbVDw/lgTxea7q5Ai66rrz+9d/14xbVt+eDQhj4gThrB+pEfeyR5ETZdbcigS1+OYKoZfzFhrPrPh37AVGE2uhX2M38+ElWk01y402rGw5BfcX92vjbcKFDrmTefRc6s=
  template:
    metadata:
      creationTimestamp: null
      name: elasticsearch-es-elastic-user
      namespace: observability
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: observability
spec:
  encryptedData:
    admin-password: AgDBjknP+ktYJUteRyeR4Upd9uo0PsN3YAqArt1PXyVgqXEUReEn6WVUSt2U9bGhnfaMHuon5ph+aojQUoNn23WBVbS4D3CJEKBkD9GOXq1h+G9ApA7uUYZw7U4HT4mfJcv5VDpC005jEyo4egqhfHyS4dYC3YPyTRzw+5XfSi4HmSo6K7DI25LWQ3AB4wkpbBlrANp0JXTPBdcxV1B+bmwJttFqtEUQ6jQicHzDrY/bHKxFCFr+8qpLlvXoWDOqYy5Xn0ySX2S48LMKyJdPc7+qDqo/K92/C2VGia7Kq4YUhmAR5VkKAMg6KU9pONrz11PbXp3MFRPforo/pVvsrEjOai8K6g48XMmE2dXMUODQ8IatB1HfDo/n52EtbeLeK9+pP+/e7vNEFtnyPh3XtcFfpHdBGQPNdbAVfimQdweA6GJuWHiOzK8+GNdisk4VkUekHYP50plS32w7uAGePa/rZNGHA2MFCoF88WU+FEVuDn5mmtYORn03kbutTi9T2Rukic7oRkzuqf/8ZakV6ng8G2fckYW8aYM/LMQPXf4DGftIW83us6ym72swNB1ND705qsJLuy6yKNkXYV02+Yt7s4ocqfUyjQqx1IyVvFt5FF6EE1tDYpAI2nFHTOK/Hj0M0DvcI3luNUerNDP/cg9T0ElkpvrgCNPl2WsRzL59GORfaWnPJmcSv7kRFPR+dz1cokraoO7slGT8tRitggSz5jutywvLE/RWWdwS1ea1Ny8=
    admin-user: AgC8kgFy3/iwF0Vb8QUueW2UUQQTT35bXl5flwhpdAUZVq7VbRW5VzpwrTldg37fs0pnPhFgr3zW9fdwlp15+vhKQwTr9hYVRhki75DlmCW54nJpra/U2du1EJPYBk2XZuwkpKZvvrFIUPMl7y50E+9odx0aDcWAN6OviCd9Su3GE3utZ4CyM18eGaFFD0rvPUtAIlO7SnO2AW6n665XneoEdxsVRHx8Gw4FrnpYWR21UFn8cKyPspDFaSQzBBkq5YkhSmSS3PJrd6HqzpQiN4UO8g7/T63ry4rYLO5sW8LYg2tT6XcS5bfIkGPze7tAY7rHhFrO3jX4z04OUSBY7FyFsPn7d5X/pIdrKLEOoTbRbeg7NVDK+vbZYhy5bSUvu6hIzdWztHXTA7AfOCSoyHURBNl0bqgJXkjTfFuHPkyJDjYZkJIEpU3AX3S+emCGhM6tFeTzpbYAL016n4H/GQhZW+GAxL5zCetbFkGgW1Z2QUryxN4TRoSVRE/nZoClAT1cTyuK4I7x55uF7FFRwNCfKAezR4P/b9v8CzyHsml8poGprt/KwThe7gd25Axkc4iu2tgApV/arDUDtesnJUQMMC3cXL4TK67nhcQxFs6meqDQR1d3MLaC01hiqdGF6zpInku8LJJthNto9Esw73sLmb1amj2szJDZYtUDS4DRLYprH06niwVGFMtfBFd9WwyUXuIMbw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: observability
    type: Opaque
