apiVersion: v1
kind: Secret
metadata:
  name: rrq-secrets
  namespace: rrq
type: Opaque
stringData:
  JWT_SIGNING_KEY: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDkwjExp87fotUH
    JhTtjRZbo4m4U+2B8OgnADWMBll2Dtxuw09LyFqs2NKX/LWVkq+uGdFuYbugwrqX
    7kHIu6nXKK64MKYfkgZDNJMC8kKUCoOxsPZsRA/JUaz7WG+MF4MxjmK/fD8IQl7Y
    o7Rv0dJ9BqUVhuxTfpCnAE4FxcXfRzN2TVFRQvlOgkOoUoE89DHEYGOrolKo0dqd
    B0rFVRulZKfCVMhKNx38yoCA7+XG5MC7ix3milAjUyoVJmV27Cf1hl9VO8Cyeua0
    2LtS4H9C3nUMylLG0uf+yMsPlpk+8sGa5+rArwiZPlbgyGGlvvIjNp+hFtU3Pus2
    O7s3znqLAgMBAAECggEAAwpNqxJG3pQEbsbjylBwtqESyH9dDbgM7c/D5muDLt19
    sn8oA6LTCa8MBXcXVriPWyn+rY/g9X8BCdnhx/Aujqx8vffvjUXcjXIabhSYK+2D
    2I24iLHS3+MVAHYpbVw2oyb4SwE0uUBgkFKEqGPKf1ziPsn/RBDPjViksNDzE0eR
    ic49Txjr+5U50543cmRgBHIp4rIH2tI2SdM0YCnAzESeAkJdRYvbZXLHmet+CQfP
    ZyfUTJGPOoeunrBRNkHw/GpgiwuOD56i7XknGmGR6OXV/lUS6Py046vWC6TTpJa3
    5Si9sOz4tf0vNzQeK2xx0GBQC14j+4Kvk0FfxdR7IQKBgQDyyQTb5lEh1GIqJ/Bp
    jntxShqKW3m4pNFoV+UD4BUMN3id6GeSGt2pj6bzlcMM8Y3WHMxk8HmXpqFhAYLk
    +7bFNopv+0fV9szCVlwYdEfv8yGJ8ljaCYOFKj7GltTQ3UJef4oSviiEqaT2lfIm
    upKl4bDXoreNhhS0chW9cQPmsQKBgQDxNbmVD8NhLMOwnqTKynIqVvMpTKf/wPgv
    PxxW8+h8K/aJvZngrpOqtfpjRWEtU8S2m3GVR9C07w28n4+LeynZ+HwYFNqb6Z6y
    l3uVx8REhQLm8GTDFQJqp6acSOLpLY9TkL7hOB39CmBL5e0Lu6wUwjhbogdL6M/0
    8k7WVPi7+wKBgETFdD7l6q1uf6/5SDxeQ9E/cG0opD4NUdQAsbp7Svr+64evQUc9
    nPRe4Ke3EF0mP0sbNTqSc57lcGkOCIncU1Vhsa0uvJZ7Jl0WIVg79/ScJi/xGgIJ
    F9wsr0OJjhbr1dT2w6Gzg76wXy4KI2GdD9U1LOaoDN5l0I+ckVPsI3LBAoGAcVdo
    Y9WrXh8VuQlir/Oe36xJyE8/5dp8BF9oZqdnx+k0iJayFrSRqLan+DuipRTmq1Ox
    dI7xUAPAdbCYV9dA3C55ySsLahXFv2+U39WlsPi7W178Sfq2Tv2GOYu6LA1/eqna
    N6QR21Qj2aYp08iU3JBCwTQKr62vAg9V4jq9Qj8CgYEApyaDZgEgjkin8yB63iMm
    hyvctaIIyl8aunWmshKFA1UFc8S+UDTMgvlI67yH4CbHz/gEZI1Y8cDtG6JwNRYX
    WbB4ALXz0ma/WAfMeiWF1uW+H+fAAB2L5Enauw/kixHwY6l/DkJhYS+9pI0BRHca
    k1b63jHmbjChfQbXMO1j4yg=
    -----END PRIVATE KEY-----
