---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rrq-secrets
  namespace: rrq
spec:
  encryptedData:
    jwt-active-key-id: AgCgPbUxmxzvtMEH7ZNjQ3MSDastTa+CcWP3z/AhbBaq9cT0/UkSc+4O7pTYf4+cSCSpOp+r9VpIZhfrhkayzDVaB2/l0oMjKsxqNTZM8KPeTj+74ELIcblw4xvGc5MgULnZgfYTamfZAE9sJkPF84B6dIezw4cZ3ljWrGp1K6Tsg5NIgSx+OVHBs1Ggi75PgJRJVUqq7ZNeKqRiCmd1EVtkV7DM24fs1IYKSV0TIVSskW1kYObvV4WAbrfIMbCBERuNtPGfjZThhS534MOvz96LaaXb5jxS2DWy01XR3uiTn+ZYnxjS44ENzKfH88emueFKlaV7lQcylO9MgbyGmm+iBTthhRRSOYuCMdDOru/MlJDKfdy7IB7D4ahmTLtv8yuCXorqavqqnC/DA0xOR6eMx6E71wXK6ee3AZF/I1Tzqndm2cZXTcKY9DoqWr8cXV9Qquc/A/KOp9OMhezbgHJrm6Wb3TX1juQFsLk8mHX8x9AuiD6LzEOTIEvmKvtUlPv2wiKw+PaRjukH4hdF/X4CSLrpfwnEf9Tx4QhRd5xHnlLiYT/vV9st+YAqtewY4nExF696heAV1LwtNqkfHbkW7CgbPhMlY8qo5h8FkVWxP6nQjw4vRTblGfqA1nC61+1YxjDOWYg+/XTKEY9MfXzSK9vJ8DrA2dlVtmfSssMA9Ej3V+fXxYIlPcN/FyTx+iL523YYRsef3QWkQw==
    jwt-signing-keys: AgCrMIpqVXDDzsqOwSHa1CY2CDH0tB+H79gegEEdTqj9Iv79qDUcjEQiGWnHmmeg9sMDC2ZZgaFwFTKK072ytmhRaEP1eEK9rYhQDfItEP4r0d9O/QY/3YDeJOhWi2GiSyeVa2cSygbyU3RAhhsa7i58wB0fvDoA0+DEl4COqIxWj1TZG4ltjqN7bmixYhNMPVNHSyBHIPePmyzVQqsPzUmWSjZ3S8RaZU3Rw1DLiWw9sfKVw+EaBzCdWn+/3znkt8kLLishlTW7vsULzJuCF1gIw7xjsNRpT1xTPeNLgX+9iTD7octG+30uw+roHvgmS6hSxAVaYdjGnRNCDiM0JZ8jkSjpnRKNF1f4HStmWGGjaQCu8xvfzPXbrVCO9mUgvjSaVrrlDsDEMnzDS8qrk2fI973REWBN5AdfCatZLG4Fxiq2EBXD5xujEjp6qdMgxCgC3AdywoswNJtIU2qdQ34VLt2QwkbheZSKjHPh81QUW6Nhv1ObZLXWS+XO3bgB01nwaYZrHsJjue7UdGWhl6qtXOyENgyJkvvhupB9lbYgddiv97enpZbKFTKYj3PX2D0q7VQjxZ3zUcAy7Vx4VG4JfofstEo8tlhy2CMzMwaeGmGagpzSAx2sKWmsPbGVoGFmxpqKIyOuSiyrMYlMfL6m63nZsbKECH307XAK1dBES0SUEyeoXCRniSnRdeFvwswO5KgHSglexT7j0qmqCxn4qNKUt0itgxScS3OeamOc72ArNnrkJyJMlOk1Fl4LfjBYhoc8SJUH87uMEC+H/SEbIizapZWzAJQ0+TiLTu216ZVOVB66/Ket0WxNjcteePK+luk6vxXxXJmozODPtA4iugpQAVGPxKLa8uzUor+sWPjt9AUVRQ9noCeJqoWXndkxD9dgdZlLID5pXYb/5AtadCxxxkQE+EXR7o9bH5YlJe/hxCPjGmndEU7F0qTSbQ8amFvnkp8jt5DVBT1R+OxSr0nV+x7j6yM3WlpnnH6+g5bJYUwL6BS9VJMyvPKWNnPcmNBQYBSoEf2WgDJV0UM3Glv8Tn1j7WYylKAAQwH7hJrAlMuEfJIuWWKzDtt/XKsjx9MWrN7XH4d8/D2SS0jr1KKZzVQpTuo7onq4sSYqKUf0Qh8+P7qbX3QwqKm4L9Xp04WkD/zkDaOkxRMVt9PhkNgWED89DowbDjA0DdJdIIpvdjnUTh6QOvxRsIjO8Gor0p3p2Yl5VfvrJqpmylZC7Mc+v09w181uB3ExYYaWokLKh0qcxSC1LHtGDTYTiDxPt2qfa45Jf4BV08rlazoNi7mgbbetRYm61z25UNtQ4NyfxHYXhHZ7wUs2mx1kXT+zyUlWa7Q9Yb+juf9SKggBVA33LTI1rSxpgIOiqp95IIRtCvvMrPYT1JcO
  template:
    metadata:
      creationTimestamp: null
      name: rrq-secrets
      namespace: rrq
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: redis
spec:
  encryptedData:
    redis-password: AgB9rQPkVxy69H7rinApuaiBGF9jEKdzO8nXuKGdzOv1JzRu5JPDaqLcARvYeMmTrmF1fJ5T7Y7NGMn9XKgP00Uh3dgvvmczenolgAavai7BaWcsuIJTNBCkBtp/9nNb/c73Kx4+6zPbezhWqWT2YRDW4bi0y+T+bbtNBUlr9JPedFrkqVLeMXgK4K4J0oFK/30xyCjPYKCK5A0yv//cj2jglBcyIRMO0+CPChjtDe5GfgrQK2DzMCnJrXKOngecp8oNU05AtTeqMMWSz/zo5j452tvTst3aTBL8m0xtI2hjUTsX2Z81XlUOfi44s6e8Zf/HVz+FiMgwdDgue/cXB5yVMXtEHz+BBsIJGhQtR7N8kMDyUvx0zVLokDtAgr+4QfH7zzqdLHj1pLD/TjhME5WMXNLtk77eqZCx+WUtdaiYw2bXEFkSapjZ8TJeNCM+YfYMMGWZi+pFucGMKHHswF7OmWNHQWxiyUPAoh7fFu8sJ47hMR05+PFAirN3XLGS6s3iHQp+VPCdoeyCjNCUvID/4HVpv//3eWkxKHAev0X8yhlQ9R5lG799Fw1y/CA7T8NxYtBjZJncEX5ftJXsiI8m0BeT+HxAbOhIhSv8oosBp2i0/k35z1UvDcn5/lsKRo0rnVwzAHD5TQ42cCZq67Zmjl6oa2IK1lLgCp23v14ST46pjSP6l2UeVxwIqiUnme2zL0dtU2nacbg9ZaUyPp2JSKkMnUlm8SqRVMlQwekR
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: redis
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: rrq
spec:
  encryptedData:
    redis-password: AgCPjmjj+yZBQcDfWYA4mZI6XtYYMTgCdT6EdHEABrpjc0hUEhAWZnlnK/3NEx96fu4XYKoKvsjkK9Kow14Tf5mTlJYjZ9ysR+kKpr9HWPlV88n6vnBZAbTTWDEVTmjaXqSFU9g3bFHw1Qulis2spyFb5rocfs5s76Ry+2BcbaYRUY+2yqKP8Rb0QDd3gaUVa4uzSon2eSbgRiLj2ZFspi8W92dKYtvc5AIzs9WmscSMPCQYhGc7Akwl9byJXdPfD5s4frU2hCGCJIdqoZjvZXP7CJAyVjupG0Io0Xogn3nvz7G5r2dNHZ7/KjptYYuja24uGQkMuptwOUOBVHUOmzF2QPXV7M79pTkX3zwWwqSAJ+CDJkAaWtGcmb2fWwVCysCcb4YTVhq+xFBcetbt6SLFRyY5vYmgkHA9qfChEHKd2dziUwA2HXjd4Z9s24TBM/rg/Wlv/7YDvJy4o6fUddwDtnL9o8OdZC0RWRTT/Vxru0yuh5FWpMV1OQRyD+4u2vROg6yvtwH2sR2/bRHXojK2mvcP/jy3Bd6HVM2IqmP6l+RrRZoP4AnpDTbRsbQRw5N4ysDcyvHi+wWyybJD83xGJfRgewkW8Hy5GyyXrvygK+04//9eq9dHPh1Sqq/SZALBczRuRJviw3Q+NvKENU7ByrFpp9Z180X7eNiQz/ez6IfmQNp243Fn/3QJ4EONn57wlNYsMHf+Vn8MgbYQHu8vNkGnHdcFizeU4a5/JUKX
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: rrq
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-webhook
  namespace: observability
spec:
  encryptedData:
    url-critical: AgA7zylSI9QKyKh/mbDbsDhEeprn2es26VkBwxEwTFUPoIiRmTEJlkxuTtoU6BFzfUu4tDWPLPf0vxLJ4dToxGooZjdsEsEsY42IHVkn6s00qth081Zo+jTvJaqI9Xn3Ao4IOBMcsofVhxAg67NDn415/I/oIDAiAi+FM2p2sbtTsCEQlBgJGtDPYrRSpVeeBg4CZ2b/fmScUMz3+Rvp/2NsY4eSTcvyOTPV8NwEJVrKDfXnqo/tN5dVY1w2d1HjuMhNDdZfvuKY/qWoz+6PgrQogo2ST9LkVgL6IDAUKJiL6JS0lmYUNd54ywq7sB6fRez1qqSMiGiobdRKYPbcffR7+EiTd5E1KA6cCp0JSbdhvylnKp20PtDFEtmzBSbXsGtcJIOM1y/GzLo99EKtWmonXvHmQ5bsFBbwGCPs3eDyD4kb3mCHblN0FKFSF4ahqjgCOGrH2B7pKrZ1yfs8AXLTK6tp2CKDQI5WO5AaL+WOi642axmkmVJoocR6nrIYz5CqZ8TNY7OQ+Ud39CTnGoWq/I7JSTbxw9YH1mpRxrBZ6oyu3CTcJp3ZLtdDxsJd1PQSH7Eh/ueKgztBVoZKfGKkuKQnihzEQTSd2yqP5OLiOPLqPWbfnQOmp6J8e11mZslSVZ5EkMATM3qNETkDl01yO0WmzPMDjOS3mOEytfU8gstjH4or/FH8lrIGt7VIXt1UnR1vivbTG0AyjyuSVjNVYs0hHjQxNGcOTFwuhecs0ekC+g008L6Atyc5mYuzDCsTcASxUsOn/A3Xg+y3HEP9iK6P8oR1DU/tRJika3Te42A=
    url-warning: AgCU/pfhA2PBgOGbjc3XwKzZMl48yxYwIF7cr1RIlAYdubBj9eOWe+U0S59lUHPvZJilUv2nlxYFbgmfyvq2fQS70d9PU2bblyzcJK1pwT1gFvzkrYd2G/zk9RbxklarobW+w7ZNMkg2sgXaQCMY8fy5FwhoK16K0DcuZ/Jgptm9FFMv0inR3Rtsg7BXlgESGaW+cXvdJ8HUZSG52Wr/rYImXLpbeUWtSV6jj8KaWFqZgITJn8xA9y4hQxm5ssz5S3LCtKQNdu4So3Z+e2neNV7hKeQvPCJUr2EcMvpgpPBsWk7PHbZjoPsJNfTvLQaQqWF/VuFXeuBXKdFvmLWQhz7VTx3p5FOFtGJi0CleLIGjj+PdDPjldz/RWaOvtWYnlUYvbzWbWsjX0w5wygOeJmMwaH75QsPdmfCCLf5G5bKTgo0a65thnUu9t3JGujrTmAy6O2++fAVuzVLDrmjpQzsKxCzAmYakKgCBArEnU1sDQUbz3JV/BvZzeWTFdB2BkzhF9Auto9tw0iGJ2PgSM+FYibdxflU6209JT2tk45vXgZ/evZbjgXMwMYNG/xNfukhGhw0xizZsfTcojVekwboceZ8JbZs+Je0WAYk8DNf74mQ32kchNCxOZ/OFZw+ObXLTduUbfVKAXzlfY0Yirha0AwH0t3CNjUCMD7XB1YPjJzvWuX8zTKOTwcnuE3YX1A8VCVo+W7M5yeyILB7bc3bb30WW/A1kwLzhGwSVttedioyCM1rj0cNSDUWsSiORS9rTnGduTddcMVT1Ciw4DjctzcObDt+5fbwR1bcltNg2+eg=
  template:
    metadata:
      creationTimestamp: null
      name: slack-webhook
      namespace: observability
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: elasticsearch-es-elastic-user
  namespace: observability
spec:
  encryptedData:
    elastic: AgB05c1LVKZ3hvhkNR88OV1bLQv0SyroN9dJS7To7kYewqJzrq0DYI/T/fh0ohShxBOgvpN2C3x6SDuBBX6nQSbbuX7Fd510hwy1Ryp7w3tCOwn2n0qVlE6BtBmjAoyF6YCpT1tWvlAB1erUSGVY8vgTHKw2suD6fGOuDveE2k8E8QQcCNy3brZpJFyZt8MXwIKOD9a9RyDx+D4Fn7QpHg17GP5uMcZ4YRn/+dY07P5380yAE5blPO66TMSDy8tyw272CSKpp89BqWvIJrB65zGUMTwujYiHZcBsyYhSG/vvWs+qD/KbP+wGQEoga6oRkO6M7VPbjE4HKQOSZOC7jyEgs7EKwJMxROScNVHFGX+ZiqWFeUxjmETY/W35nVjOhsqudckTSt5tmLxTXQqH0J7JOJ0sKAysMzBZinWAnhAp0V4/0QI7Z8mizcEpilEyKwcn10UsHCzTel+a1gb1v9ZZFjWfYLiI/GqR9WSl4vg6toL13qm9f15aOl/n07VWGmpE5XMdzOYHQdIt12/PmFikdqnzf8noCgwwViD5IhbL59l9qxN9OyugzyRNGiatXylnIyNSfeJX1mTYoHoXtrbyYEqwFgaElwSdcGr9WVw69fN44blSdcrAFE/0qx3QR1F5ws1b+scVX4Ag977EtJd+2HTk8KCTZbTPmz/orwW4Pe41GGOY+EwVJm4lIQ5OqM4iE0cetBJQYs80sOLWy6yLscfjFkgOWC6c02Qe0DRx0Yvg+I+2LirteZC+DffD+8SEXC+WQM0Qk5xnJW/0vimG
  template:
    metadata:
      creationTimestamp: null
      name: elasticsearch-es-elastic-user
      namespace: observability
    type: Opaque
